- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-12 18:38:35'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: AggM Applications | CSSA
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://cssanalytics.wordpress.com/2010/01/05/aggm-applications/#0001-01-01](https://cssanalytics.wordpress.com/2010/01/05/aggm-applications/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'Well, I wish I had more time to expand upon all the indicators presented on
    the blog. Fortunately there are many DV Indicator community members [http://www.dvindicators.com/](http://www.dvindicators.com/) that
    do just that, and find applications that I have not explored myself. There are
    a lot of smart people out there, and I always like to promote vertical thinking
    and development. One community member and fellow blogger has tried a few applications,
    and even demonstrated the robustness of DV Indicators on the UK’s FTSE 100 index.
    His blog is Mind, Money, Markets is starting to gather steam, and this week I
    plan to add him to the blogroll along with a few other good new blogs. Here is
    a very interesting application of the AggM which is a composite trend and mean-reversion
    indicator– it shows scaling in and out beginning with favorably high levels of
    the AggM and exiting at low levels. Madoff himself would be proud of the equity
    curve: [http://davesbrain.blogs.com/mindmoneymarkets/2010/01/agg-m-scale-in-out.html](http://davesbrain.blogs.com/mindmoneymarkets/2010/01/agg-m-scale-in-out.html)'
  prefs: []
  type: TYPE_NORMAL
