- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-12 18:38:35'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-12 18:38:35'
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: AggM Applications | CSSA
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: AggM Applications | CSSA
- en: 来源：[https://cssanalytics.wordpress.com/2010/01/05/aggm-applications/#0001-01-01](https://cssanalytics.wordpress.com/2010/01/05/aggm-applications/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://cssanalytics.wordpress.com/2010/01/05/aggm-applications/#0001-01-01](https://cssanalytics.wordpress.com/2010/01/05/aggm-applications/#0001-01-01)
- en: 'Well, I wish I had more time to expand upon all the indicators presented on
    the blog. Fortunately there are many DV Indicator community members [http://www.dvindicators.com/](http://www.dvindicators.com/) that
    do just that, and find applications that I have not explored myself. There are
    a lot of smart people out there, and I always like to promote vertical thinking
    and development. One community member and fellow blogger has tried a few applications,
    and even demonstrated the robustness of DV Indicators on the UK’s FTSE 100 index.
    His blog is Mind, Money, Markets is starting to gather steam, and this week I
    plan to add him to the blogroll along with a few other good new blogs. Here is
    a very interesting application of the AggM which is a composite trend and mean-reversion
    indicator– it shows scaling in and out beginning with favorably high levels of
    the AggM and exiting at low levels. Madoff himself would be proud of the equity
    curve: [http://davesbrain.blogs.com/mindmoneymarkets/2010/01/agg-m-scale-in-out.html](http://davesbrain.blogs.com/mindmoneymarkets/2010/01/agg-m-scale-in-out.html)'
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 嗯，我希望我有更多的时间来详细介绍博客上提出的所有指标。幸运的是，有很多DV指标社区成员[http://www.dvindicators.com/](http://www.dvindicators.com/)专门从事此项工作，并发现了我自己没有探索过的应用。世界上有很多聪明人，我总是喜欢推广纵向思维和发展。一位社区成员和博客作者尝试了一些应用，甚至展示了DV指标在英国的富时100指数上的稳健性。他的博客Mind,
    Money, Markets开始引起关注，本周我打算将他添加到博客链接列表中，还会加入其他几个好的新博客。这是一个非常有趣的AggM应用，它是一个复合趋势和均值回归指标——它显示了从AggM的有利高水平开始逐步增加和减少，并在低水平退出。马多夫本人会为这个股权曲线感到自豪：[http://davesbrain.blogs.com/mindmoneymarkets/2010/01/agg-m-scale-in-out.html](http://davesbrain.blogs.com/mindmoneymarkets/2010/01/agg-m-scale-in-out.html)
