- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 06:26:25'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Application Timing: GPS Vulnerabilities | Tales from a Trading Desk'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://mdavey.wordpress.com/2013/04/24/application-timing-gps-vulnerabilities/#0001-01-01](https://mdavey.wordpress.com/2013/04/24/application-timing-gps-vulnerabilities/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'Application Timing: GPS Vulnerabilities'
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: 'I see [Symmetricom](http://www.symmetricom.com/) is running a webinar on “Mitigating
    GPS Vulnerabilities in Network Timing Applications” which maybe worth a [watch](http://www.symmetricom.com/company/news-and-events/webinars/). 
    I’m guessing they will cover:'
  prefs: []
  type: TYPE_NORMAL
- en: GPS Jammers – Illegal devices
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Solar Flare Activity – Geomagnetic storms
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Unintentional Interference – stuff breaks
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: GPS Antennas and Cables – remoteness of installations
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: ~ by mdavey on April 24, 2013.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [Uncategorized](https://mdavey.wordpress.com/category/uncategorized/)
  prefs: []
  type: TYPE_NORMAL
- en: 'Tags: [PTP](https://mdavey.wordpress.com/tag/ptp/)'
  prefs: []
  type: TYPE_NORMAL
