- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 05:48:31'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Camel in a Vertx Web Application | Tales from a Trading Desk
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://mdavey.wordpress.com/2014/06/26/camel-in-a-vertx-web-application/#0001-01-01](https://mdavey.wordpress.com/2014/06/26/camel-in-a-vertx-web-application/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Mixing interesting technologies to PoC possible solution is always interesting. 
    I’ve become a lot more interested in Apache Camel over the last time period. 
    When I realised there was a Camel Vertx component, and had time to open IntelliJ,
    I thought I’d build a quick and dirty application to look at using Apache Camel
    from an up-stream integration workflow, and websocket’s for down-stream browsers. 
    Although the code is ropy, it hopefully provide some food for thought.
  prefs: []
  type: TYPE_NORMAL
- en: Easiest way to being with Vertx maybe to [generate](http://vertx.io/maven_dev.html)
    a project with Maven.
  prefs: []
  type: TYPE_NORMAL
- en: '[Smartjava,](http://www.smartjava.org/) Pretech and hasCode provides a few
    interesting articles to assist:'
  prefs: []
  type: TYPE_NORMAL
- en: Create a simpe RESTful [service](http://www.smartjava.org/content/create-simpe-restful-service-vertx-20-rxjava-and-mongodb)
    with vert.x 2.0, RxJava and mongoDB
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Browser to browser [communication](http://www.smartjava.org/content/browser-browser-communication-vertx-websockets-and-html5)
    with Vert.x, websockets and HTML5
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Apache Camel + ActiveMQ [Example](http://www.pretechsol.com/2013/08/apache-camel-activemq-exampe.html)
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Spring JmsTemplate and MessageListener [Example](http://www.pretechsol.com/2013/12/spring-jmstemplate-and-messagelistener.html)
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Creating a Websocket Chat [Application](http://www.hascode.com/2013/11/creating-a-websocket-chat-application-with-vert-x-and-java/)
    with Vert.x and Java
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'The code is “rushed”.  Enhancements:'
  prefs: []
  type: TYPE_NORMAL
- en: Camel [aggregating](http://www.amazon.com/Apache-Camel-Developers-Cookbook-Cranton/dp/1782170308)
    of messages – example use case could possibly be messages from a number of trade
    repositories that need to be seen in a users blotter
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Camel transformation – Java and XML to JSON, as the upstream integrated systems
    are most likely not going to be JSON’d
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '[Famo.us](http://famo.us/) + [Angular.js](https://github.com/Famous/famous-angular)
    to improve the basic UI'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
- en: '[PRE1]'
  prefs: []
  type: TYPE_PRE
- en: ~ by mdavey on June 26, 2014.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [Data](https://mdavey.wordpress.com/category/data/), [Java](https://mdavey.wordpress.com/category/languages/java/)
  prefs: []
  type: TYPE_NORMAL
