- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-18 05:48:31'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024年05月18日 05:48:31
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Camel in a Vertx Web Application | Tales from a Trading Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: Camel in a Vertx Web Application | 交易台的故事
- en: 来源：[https://mdavey.wordpress.com/2014/06/26/camel-in-a-vertx-web-application/#0001-01-01](https://mdavey.wordpress.com/2014/06/26/camel-in-a-vertx-web-application/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://mdavey.wordpress.com/2014/06/26/camel-in-a-vertx-web-application/#0001-01-01](https://mdavey.wordpress.com/2014/06/26/camel-in-a-vertx-web-application/#0001-01-01)
- en: Mixing interesting technologies to PoC possible solution is always interesting. 
    I’ve become a lot more interested in Apache Camel over the last time period. 
    When I realised there was a Camel Vertx component, and had time to open IntelliJ,
    I thought I’d build a quick and dirty application to look at using Apache Camel
    from an up-stream integration workflow, and websocket’s for down-stream browsers. 
    Although the code is ropy, it hopefully provide some food for thought.
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 将有趣的技术混合起来进行 PoC（概念验证）可能总是有趣的。在过去的一段时间里，我对 Apache Camel 的兴趣增加了很多。当我意识到有一个 Camel
    Vertx 组件，并且有时间打开 IntelliJ 时，我想我会构建一个快速而简单的应用程序，用于查看如何使用 Apache Camel 进行上游集成工作流程，以及使用
    websocket 用于下游浏览器。尽管代码有点粗糙，但希望它能提供一些思路。
- en: Easiest way to being with Vertx maybe to [generate](http://vertx.io/maven_dev.html)
    a project with Maven.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 开始使用 Vertx 最简单的方法可能是使用 Maven [生成](http://vertx.io/maven_dev.html) 一个项目。
- en: '[Smartjava,](http://www.smartjava.org/) Pretech and hasCode provides a few
    interesting articles to assist:'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: '[Smartjava](http://www.smartjava.org/)、Pretech 和 hasCode 提供了一些有趣的文章来帮助：'
- en: Create a simpe RESTful [service](http://www.smartjava.org/content/create-simpe-restful-service-vertx-20-rxjava-and-mongodb)
    with vert.x 2.0, RxJava and mongoDB
  id: totrans-9
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 使用 vert.x 2.0、RxJava 和 mongoDB 创建一个简单的 RESTful [服务](http://www.smartjava.org/content/create-simpe-restful-service-vertx-20-rxjava-and-mongodb)
- en: Browser to browser [communication](http://www.smartjava.org/content/browser-browser-communication-vertx-websockets-and-html5)
    with Vert.x, websockets and HTML5
  id: totrans-10
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 使用 Vert.x、Websockets 和 HTML5 进行浏览器间的 [通信](http://www.smartjava.org/content/browser-browser-communication-vertx-websockets-and-html5)
- en: Apache Camel + ActiveMQ [Example](http://www.pretechsol.com/2013/08/apache-camel-activemq-exampe.html)
  id: totrans-11
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Apache Camel + ActiveMQ [示例](http://www.pretechsol.com/2013/08/apache-camel-activemq-exampe.html)
- en: Spring JmsTemplate and MessageListener [Example](http://www.pretechsol.com/2013/12/spring-jmstemplate-and-messagelistener.html)
  id: totrans-12
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Spring JmsTemplate 和 MessageListener [示例](http://www.pretechsol.com/2013/12/spring-jmstemplate-and-messagelistener.html)
- en: Creating a Websocket Chat [Application](http://www.hascode.com/2013/11/creating-a-websocket-chat-application-with-vert-x-and-java/)
    with Vert.x and Java
  id: totrans-13
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 使用 Vert.x 和 Java 创建一个 Websocket 聊天 [应用程序](http://www.hascode.com/2013/11/creating-a-websocket-chat-application-with-vert-x-and-java/)
- en: 'The code is “rushed”.  Enhancements:'
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 代码是“仓促”的。增强：
- en: Camel [aggregating](http://www.amazon.com/Apache-Camel-Developers-Cookbook-Cranton/dp/1782170308)
    of messages – example use case could possibly be messages from a number of trade
    repositories that need to be seen in a users blotter
  id: totrans-15
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Camel [聚合](http://www.amazon.com/Apache-Camel-Developers-Cookbook-Cranton/dp/1782170308)
    消息 - 示例用例可能是需要在用户 blotter 中查看来自多个交易库的消息
- en: Camel transformation – Java and XML to JSON, as the upstream integrated systems
    are most likely not going to be JSON’d
  id: totrans-16
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Camel 转换 - 将 Java 和 XML 转换为 JSON，因为上游集成系统很可能不会使用 JSON
- en: '[Famo.us](http://famo.us/) + [Angular.js](https://github.com/Famous/famous-angular)
    to improve the basic UI'
  id: totrans-17
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: '[Famo.us](http://famo.us/) + [Angular.js](https://github.com/Famous/famous-angular)
    以改进基本的用户界面'
- en: '[PRE0]'
  id: totrans-18
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: '[PRE1]'
  id: totrans-19
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: ~ by mdavey on June 26, 2014.
  id: totrans-20
  prefs: []
  type: TYPE_NORMAL
  zh: 作者：mdavey，于2014年6月26日发布。
- en: Posted in [Data](https://mdavey.wordpress.com/category/data/), [Java](https://mdavey.wordpress.com/category/languages/java/)
  id: totrans-21
  prefs: []
  type: TYPE_NORMAL
  zh: Posted in [数据](https://mdavey.wordpress.com/category/data/)，[Java](https://mdavey.wordpress.com/category/languages/java/)
