- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 06:07:35'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Configuration Services 2.0: Early Oslo | Tales from a Trading Desk'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://mdavey.wordpress.com/2008/05/20/configuration-services-20-early-oslo/#0001-01-01](https://mdavey.wordpress.com/2008/05/20/configuration-services-20-early-oslo/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'Configuration Services 2.0: Early Oslo'
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Interesting [read](http://www.informationweek.com/news/software/soa/showArticle.jhtml?articleID=207401732&cid=RSSfeed_IWK_News)
    on [.NET StockTrader](http://searchwindevelopment.techtarget.com/news/article/0,289142,sid8_gci1312615,00.html)
    – offering dynamic clustering of nodes that run services. Video available [here](http://blogs.msdn.com/gregleak/archive/2008/04/15/putting-the-final-touches-on-net-stocktrader2-0.aspx).
    Distributed “Service Network” offer a hint at where Microsoft could be heading
    with [Oslo](http://redmondmag.com/news/article.asp?EditorialsID=9793). Download
    available [here](http://msdn.microsoft.com/en-gb/netframework/bb499684.aspx) in
    early June.
  prefs: []
  type: TYPE_NORMAL
- en: ~ by mdavey on May 20, 2008.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [.NET](https://mdavey.wordpress.com/category/languages/net/)
  prefs: []
  type: TYPE_NORMAL
- en: 'Tags: [Microsoft](https://mdavey.wordpress.com/tag/microsoft/)'
  prefs: []
  type: TYPE_NORMAL
