- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-18 06:07:35'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-18 06:07:35'
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Configuration Services 2.0: Early Oslo | Tales from a Trading Desk'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 'Configuration Services 2.0: Early Oslo | Tales from a Trading Desk'
- en: 来源：[https://mdavey.wordpress.com/2008/05/20/configuration-services-20-early-oslo/#0001-01-01](https://mdavey.wordpress.com/2008/05/20/configuration-services-20-early-oslo/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://mdavey.wordpress.com/2008/05/20/configuration-services-20-early-oslo/#0001-01-01](https://mdavey.wordpress.com/2008/05/20/configuration-services-20-early-oslo/#0001-01-01)
- en: 'Configuration Services 2.0: Early Oslo'
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 'Configuration Services 2.0: Early Oslo'
- en: Interesting [read](http://www.informationweek.com/news/software/soa/showArticle.jhtml?articleID=207401732&cid=RSSfeed_IWK_News)
    on [.NET StockTrader](http://searchwindevelopment.techtarget.com/news/article/0,289142,sid8_gci1312615,00.html)
    – offering dynamic clustering of nodes that run services. Video available [here](http://blogs.msdn.com/gregleak/archive/2008/04/15/putting-the-final-touches-on-net-stocktrader2-0.aspx).
    Distributed “Service Network” offer a hint at where Microsoft could be heading
    with [Oslo](http://redmondmag.com/news/article.asp?EditorialsID=9793). Download
    available [here](http://msdn.microsoft.com/en-gb/netframework/bb499684.aspx) in
    early June.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 有趣的[阅读](http://www.informationweek.com/news/software/soa/showArticle.jhtml?articleID=207401732&cid=RSSfeed_IWK_News)关于
    [.NET StockTrader](http://searchwindevelopment.techtarget.com/news/article/0,289142,sid8_gci1312615,00.html)
    – 提供运行服务的节点的动态集群。视频可以[在这里](http://blogs.msdn.com/gregleak/archive/2008/04/15/putting-the-final-touches-on-net-stocktrader2-0.aspx)找到。分布式“服务网络”暗示了微软可能在[奥斯陆](http://redmondmag.com/news/article.asp?EditorialsID=9793)方面的发展方向。6月初可以在[这里](http://msdn.microsoft.com/en-gb/netframework/bb499684.aspx)下载。
- en: ~ by mdavey on May 20, 2008.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 作者：mdavey，2008年5月20日。
- en: Posted in [.NET](https://mdavey.wordpress.com/category/languages/net/)
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 发布在 [.NET](https://mdavey.wordpress.com/category/languages/net/)
- en: 'Tags: [Microsoft](https://mdavey.wordpress.com/tag/microsoft/)'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: '标签: [微软](https://mdavey.wordpress.com/tag/microsoft/)'
