- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 06:25:42'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Cucumber and Distributed Application Testing – Part 2 | Tales from a Trading
    Desk
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://mdavey.wordpress.com/2013/05/08/cucumber-and-distributed-application-testing-part-2/#0001-01-01](https://mdavey.wordpress.com/2013/05/08/cucumber-and-distributed-application-testing-part-2/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Cucumber and Distributed Application Testing – Part 2
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Continuing on from the previous posting.  If one decided to annotate the PlantUML
    flows with max latency data one could then possibly consider leveraging [Application
    Tap for Solarflare](http://www.ts-a.com/attachments/apptap-for-solarflare.pdf)
    from a cucumber test  perspective to capture the hop latency, and validate the
    flows via the data capture [database](http://www.ts-a.com/attachments/Application_Tap_Product_Briefing.pdf). 
    Anyone tried such a thing?
  prefs: []
  type: TYPE_NORMAL
- en: ~ by mdavey on May 8, 2013.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [Uncategorized](https://mdavey.wordpress.com/category/uncategorized/)
  prefs: []
  type: TYPE_NORMAL
- en: 'Tags: [Cucumber](https://mdavey.wordpress.com/tag/cucumber/)'
  prefs: []
  type: TYPE_NORMAL
