- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-18 05:55:02'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024年5月18日 05:55:02
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'DevOps: Docker – Application Delivery | Tales from a Trading Desk'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 'DevOps: Docker – 应用程序交付 | 来自交易台的故事'
- en: 来源：[https://mdavey.wordpress.com/2014/01/07/devops-docker/#0001-01-01](https://mdavey.wordpress.com/2014/01/07/devops-docker/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://mdavey.wordpress.com/2014/01/07/devops-docker/#0001-01-01](https://mdavey.wordpress.com/2014/01/07/devops-docker/#0001-01-01)
- en: 'DevOps: Docker – Application Delivery'
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 'DevOps: Docker – 应用程序 交付'
- en: RelateIQ offers interesting [reading](http://blog.relateiq.com/a-docker-dev-environment-in-24-hours-part-1-of-2/)
    on [Docker](http://www.docker.io/gettingstarted/#1) usage for [development](http://blog.relateiq.com/a-docker-dev-environment-in-24-hours-part-2-of-2/)
    environments.  If you’re on [OSX](http://www.infoq.com/news/2013/03/Docker), consider
    [Vagrant](http://docs.vagrantup.com/v2/why-vagrant/index.html).  devo.ps offers
    [reading](http://devo.ps/blog/2013/09/25/vagrant-docker-and-ansible-wtf.html)
    on both, including Ansible.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: RelateIQ 提供了有关[Docker](http://www.docker.io/gettingstarted/#1)在[开发](http://blog.relateiq.com/a-docker-dev-environment-in-24-hours-part-2-of-2/)环境中的用法的有趣[阅读](http://blog.relateiq.com/a-docker-dev-environment-in-24-hours-part-1-of-2/)。
    如果你使用的是[OSX](http://www.infoq.com/news/2013/03/Docker)，考虑使用[Vagrant](http://docs.vagrantup.com/v2/why-vagrant/index.html)。
    devo.ps 提供了关于两者的[阅读](http://devo.ps/blog/2013/09/25/vagrant-docker-and-ansible-wtf.html)，包括
    Ansible。
- en: Quay.io offers another [interesting](https://medium.com/devops-programming/7f5fd023158f)
    read – What is Docker? With a suitable diagram of what is possible in breaking
    the application under [development](http://www.slideshare.net/dotCloud/why-docker)h
    into multiple containers.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: Quay.io 提供了另一个有趣的[阅读](https://medium.com/devops-programming/7f5fd023158f)——什么是
    Docker？附有适当的图示，说明了如何将正在[开发](http://www.slideshare.net/dotCloud/why-docker)的应用程序分解为多个容器。
- en: '![](img/32c7ea96d93c9f4bce8a494f3fb65ce3.png)'
  id: totrans-9
  prefs: []
  type: TYPE_IMG
  zh: '![](img/32c7ea96d93c9f4bce8a494f3fb65ce3.png)'
- en: ~ by mdavey on January 7, 2014.
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: ~ 作者 mdavey 于 2014年1月7日。
- en: Posted in [Agile](https://mdavey.wordpress.com/category/agile/)
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 发布在 [敏捷](https://mdavey.wordpress.com/category/agile/)
- en: 'Tags: [Docker](https://mdavey.wordpress.com/tag/docker/)'
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 标签：[Docker](https://mdavey.wordpress.com/tag/docker/)
