- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-12 21:05:42'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Falkenblog: 5 Myths of Social Security'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[http://falkenblog.blogspot.com/2011/03/5-myths-of-social-security.html#0001-01-01](http://falkenblog.blogspot.com/2011/03/5-myths-of-social-security.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Most lists have 10, but for some reason, things pertaining to Social Security
    contains 5\.
  prefs: []
  type: TYPE_NORMAL
- en: '[Here''s](http://pol.moveon.org/ssmyths/)'
  prefs: []
  type: TYPE_NORMAL
- en: 'the Liberal''s "5 myths", including this gem:'
  prefs: []
  type: TYPE_NORMAL
- en: The Social Security Trust Fund isn't full of IOUs, it's full of U.S. Treasury
    Bonds. And those bonds are backed by the full faith and credit of the United States.
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: '[Here''s](http://www.businessinsider.com/five-enduring-social-security-myths-that-must-be-fixed-2011-3)'
  prefs: []
  type: TYPE_NORMAL
- en: the conservative take.
  prefs: []
  type: TYPE_NORMAL
- en: Accounting that would be illegal for a private company is pretty hard to defend.
    The present value of the Social Security deficit is
  prefs: []
  type: TYPE_NORMAL
- en: '[around $7 Trillion.](http://www.heritage.org/research/reports/2009/05/2009-social-security-trustees-report-continues-to-show-the-urgency-of-reform)'
  prefs: []
  type: TYPE_NORMAL
- en: I can see QE3 coming, as the Treasury will probably just issue more debt that
    will be bought by the Fed. Problem solved!
  prefs: []
  type: TYPE_NORMAL
