- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-12 21:05:42'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 时间：2024年05月12日21时05分42秒
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Falkenblog: 5 Myths of Social Security'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 'Falkenblog: 5 Myths of Social Security'
- en: 来源：[http://falkenblog.blogspot.com/2011/03/5-myths-of-social-security.html#0001-01-01](http://falkenblog.blogspot.com/2011/03/5-myths-of-social-security.html#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[http://falkenblog.blogspot.com/2011/03/5-myths-of-social-security.html#0001-01-01](http://falkenblog.blogspot.com/2011/03/5-myths-of-social-security.html#0001-01-01)
- en: Most lists have 10, but for some reason, things pertaining to Social Security
    contains 5\.
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 大多数清单有10个，但由于某种原因，与社会保障有关的事物只有5个。
- en: '[Here''s](http://pol.moveon.org/ssmyths/)'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '[这里是](http://pol.moveon.org/ssmyths/)'
- en: 'the Liberal''s "5 myths", including this gem:'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 自由派的“5个神话”，其中包括这个珍宝：
- en: The Social Security Trust Fund isn't full of IOUs, it's full of U.S. Treasury
    Bonds. And those bonds are backed by the full faith and credit of the United States.
  id: totrans-9
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 社会保障信托基金里没有兑现的债券，而是充满了美国国债。而这些债券由美利坚合众国的完全信誉支持。
- en: '[Here''s](http://www.businessinsider.com/five-enduring-social-security-myths-that-must-be-fixed-2011-3)'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: '[这里是](http://www.businessinsider.com/five-enduring-social-security-myths-that-must-be-fixed-2011-3)'
- en: the conservative take.
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 保守派的观点。
- en: Accounting that would be illegal for a private company is pretty hard to defend.
    The present value of the Social Security deficit is
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 对于私营公司来说会是违法的会计处理是相当难以辩护的。社会保障赤字的现值是
- en: '[around $7 Trillion.](http://www.heritage.org/research/reports/2009/05/2009-social-security-trustees-report-continues-to-show-the-urgency-of-reform)'
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: '[大约7万亿美元。](http://www.heritage.org/research/reports/2009/05/2009-social-security-trustees-report-continues-to-show-the-urgency-of-reform)'
- en: I can see QE3 coming, as the Treasury will probably just issue more debt that
    will be bought by the Fed. Problem solved!
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 我可以看到 QE3 即将来临，因为财政部可能会发行更多的债务，而这些债务将被美联储购买。问题解决了！
