- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 06:27:34'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: FPGA Killer Applications | Tales from a Trading Desk
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://mdavey.wordpress.com/2013/04/18/fpga-killer-applications/#0001-01-01](https://mdavey.wordpress.com/2013/04/18/fpga-killer-applications/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: FPGA Killer Applications
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Throughput reduction e.g market data line reduction.  To avoid data loss its
    beneficial to consume both A and B lines of market data from a venue. However,
    microbursts can cause queuing delays. FPGA network adapter line arb allow the
    throughput that a server CPU consumes to be halved, thus improving application
    latency, and reduce jitter (pre-processing packets of data prior to application
    consumption)
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Order Book on the FPGA and off the server CPU.  Value-add: from cutting down
    on data that needs to cross the bus.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Pre-Trade checks.  Value-add: Off-loaded from the server CPU’s'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Storage – off the back of the FPGA.  Value-add: Off-loaded from the server
    CPU’s'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Ethernet Resilient
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Remember, reading from PCI is expensive compared to memory – hence offload to
    the FPGA can be beneficial in certain cases.
  prefs: []
  type: TYPE_NORMAL
- en: ~ by mdavey on April 18, 2013.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [Trading](https://mdavey.wordpress.com/category/trading/)
  prefs: []
  type: TYPE_NORMAL
