- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-12 17:56:05'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024年05月12日 17:56:05
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Free Web-Based Cluster Application Using FTCA | CSSA
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 使用FTCA的免费基于Web的聚类应用程序 | CSSA
- en: 来源：[https://cssanalytics.wordpress.com/2013/12/17/free-web-based-cluster-application-using-ftca/#0001-01-01](https://cssanalytics.wordpress.com/2013/12/17/free-web-based-cluster-application-using-ftca/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://cssanalytics.wordpress.com/2013/12/17/free-web-based-cluster-application-using-ftca/#0001-01-01](https://cssanalytics.wordpress.com/2013/12/17/free-web-based-cluster-application-using-ftca/#0001-01-01)
- en: One of the most useful ways to understand clusters is to work with a visual
    application and see different cluster groupings over time. In a previous post,
    I introduced the [Fast Threshold Clustering Algorithm](https://cssanalytics.wordpress.com/2013/11/26/fast-threshold-clustering-algorithm-ftca/
    "Fast Threshold Clustering Algorithm (FTCA)")– FTCA-  as a simple and intuitive
    method of forming asset clusters.  A fellow quant researcher and long-time reader-
    Pierre Chretien- was kind enough to build an FTCA Shiny web application in collaboration
    with Michael Kapler of [Systematic Investor](http://systematicinvestor.wordpress.com/) in
    R. It shows the use of clustering with FTCA on a broad range of asset classes
    that have been back-extended using index data. Users can experiment with varying
    different parameters from the time period at cluster formation (plot date), the
    correlation threshold for cluster formation, and the lookback period for the correlation
    calculation.  Another useful output is the return and volatility for each asset
    at the time of cluster formation as well as a transition map of the historical
    cluster memberships for each asset. Two images of the application are presented
    below.  Very cool stuff and nice work!  I personally enjoyed using it to see the
    impact of different parameters and also the historical clusters over different
    time periods.
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 了解聚类最有用的方法之一是使用可视化应用程序，在一段时间内看不同的聚类分组。 在之前的一篇文章中，我介绍了[快速阈值聚类算法](https://cssanalytics.wordpress.com/2013/11/26/fast-threshold-clustering-algorithm-ftca/
    "快速阈值聚类算法（FTCA）")-  FTCA- 作为一种简单直观的资产聚类方法。一位同行的量化研究员和长期读者Pierre Chretien很友好地与Michael
    Kapler合作在R中构建了一个FTCA Shiny Web应用。 它展示了在使用指数数据进行回溯的广泛资产类别上，使用FTCA进行聚类的情况。用户可以尝试不同参数，如聚类时的时间段（图表日期），聚类形成的相关阈值，以及用于相关性计算的回溯期。  另一个有用的输出是在聚类形成时每个资产的回报和波动性，以及每个资产的历史聚类成员资格的转换图。
    应用程序的两个图像如下所示。 非常酷的东西，做得很好！ 我个人很享受使用它来看不同参数的影响，以及不同时间段的历史聚类。
- en: 'The link to the application can be found here:'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 应用程序的链接可以在这里找到：
- en: '[cluster web application](http://glimmer.rstudio.com/heuristica/clusters/)'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: '[聚类Web应用程序](http://glimmer.rstudio.com/heuristica/clusters/)'
- en: '[![cluster application1](img/a22759b757b59e4b24962098fd92d6f6.png)](https://cssanalytics.files.wordpress.com/2013/12/cluster-application1.png)'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: '[![cluster application1](img/a22759b757b59e4b24962098fd92d6f6.png)](https://cssanalytics.files.wordpress.com/2013/12/cluster-application1.png)'
- en: '[![cluster application2](img/35425516678256f0b98dfa942db4dc1c.png)](https://cssanalytics.files.wordpress.com/2013/12/cluster-application2.png)'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: '[![cluster application2](img/35425516678256f0b98dfa942db4dc1c.png)](https://cssanalytics.files.wordpress.com/2013/12/cluster-application2.png)'
