- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-18 05:39:46'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 05:39:46
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Globally Distributed Mission Critical Applications | Tales from a Trading Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 全球分布式关键任务应用 | 从交易台的故事
- en: 来源：[https://mdavey.wordpress.com/2015/09/23/globally-distributed-mission-critical-applications/#0001-01-01](https://mdavey.wordpress.com/2015/09/23/globally-distributed-mission-critical-applications/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://mdavey.wordpress.com/2015/09/23/globally-distributed-mission-critical-applications/#0001-01-01](https://mdavey.wordpress.com/2015/09/23/globally-distributed-mission-critical-applications/#0001-01-01)
- en: Globally Distributed Mission Critical Applications
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 全球分布式关键任务 应用
- en: 'Kris Beevers offers some great [insight](http://highscalability.com/blog/2015/9/2/building-globally-distributed-mission-critical-applications.html)
    through a two part series on  [NSONE](https://nsone.net/).  A few noteworthy callouts:'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: Kris Beevers在 [NSONE](https://nsone.net/) 上通过一系列关于构建全球分布式关键任务应用的见解提供了一些很棒的[洞察](http://highscalability.com/blog/2015/9/2/building-globally-distributed-mission-critical-applications.html)。
    几个值得注意的点：
- en: “Unit testing is not enough.   Test the interactions between your subsystems.”
     Could not agree with this more.  Numerous projects obsess with unit test coverage,
    and forget boundary testing between subsystems.  Likewise, how many systems fail
    to test the expected number of payloads sent over the wire?
  id: totrans-8
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: “单元测试并不足够。测试子系统之间的交互。” 对此我非常赞同。 许多项目过分关注单元测试覆盖率，并忽略了子系统之间的边界测试。 同样，有多少系统失败了测试传送的预期有效载荷数量？
- en: “Automate Deployments And Config Management – With Extreme Care” There is no
    free lunch!
  id: totrans-9
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: “自动化部署和配置管理–要非常小心”。没有免费的午餐！
- en: “We roll out deployments facility by facility, from lowest traffic to highest.
    Within a facility, we roll out server by server, and even core by core, running
    a comprehensive functional testing suite at every step of the way. ”  Big bang
    deployments have implications.  NSONE deployment sounds very similar to the
  id: totrans-10
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: “我们按设施进行部署，从流量最低到最高。在一个设施内，我们按服务器进行部署，甚至按核心进行部署，在每一步都运行全面的功能测试套件。” 大爆炸式的部署会有影响。
    NSONE 的部署听起来与
- en: “Simulate the bad things before they happen. Netflix’s Chaos Monkey is one well-known
    example” – how many times have you heard IT propose no concept of failover/DR
    because they believe their isn’t budget, only to be burnt a time period later?
  id: totrans-11
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: “在问题发生之前模拟坏事情。Netflix 的混沌猴就是一个著名的例子” – 你有多少次听到 IT 提出没有容错/灾备概念，因为他们相信没有预算，只能在一段时间后被烧伤？
- en: “Lock your systems down and minimize the attack surface exposed to the internet.”
    – security 101 in my view.  Likewise, “Each role in your architecture should expose
    the services it provides only to the set of systems that need to access those
    services”
  id: totrans-12
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: “锁定系统，并最小化暴露给互联网的攻击面。” – 在我看来这是 101 的安全知识。 同样，“你的架构中的每个角色应该只向需要访问这些服务的系统集提供它所提供的服务”
- en: ~ by mdavey on September 23, 2015.
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: ~ 由 mdavey 于 2015年9月23日发布。
- en: Posted in [Agile](https://mdavey.wordpress.com/category/agile/)
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 发表在[敏捷](https://mdavey.wordpress.com/category/agile/)
