- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-12 17:38:24'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024年05月12日 17:38:24
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'How Should Trend-Followers Adjust to the Modern Environment?: Enter Adaptive
    Momentum | CSSA'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 趋势跟随者应该如何调整到现代环境？：引入自适应动量 | CSSA
- en: 来源：[https://cssanalytics.wordpress.com/2020/12/23/how-should-trend-followers-adjust-to-the-modern-environment-enter-adaptive-momentum/#0001-01-01](https://cssanalytics.wordpress.com/2020/12/23/how-should-trend-followers-adjust-to-the-modern-environment-enter-adaptive-momentum/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://cssanalytics.wordpress.com/2020/12/23/how-should-trend-followers-adjust-to-the-modern-environment-enter-adaptive-momentum/#0001-01-01](https://cssanalytics.wordpress.com/2020/12/23/how-should-trend-followers-adjust-to-the-modern-environment-enter-adaptive-momentum/#0001-01-01)
- en: 'The premise of using either time-series momentum or “trend-following” using
    moving averages is the same only the math differs very slightly (see [Which Trend
    Is Your Friend? by AQR](https://www.aqr.com/Insights/Research/Journal-Article/Which-Trend-Is-Your-Friend)):
    using some fixed lookback you can time market cycles and capture more upside than
    downside and therefore improve performance vs buy and hold OR at the very least
    improve return versus downside risk. The problem lies in the “fixed” portion of
    the description: markets as we know are non-stationary and business cycles can
    vary widely.'
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 使用时间序列动量或使用移动平均线的"趋势跟随"的前提完全相同，只是数学上略有不同（参见[AQR的《哪种趋势是你的朋友？》](https://www.aqr.com/Insights/Research/Journal-Article/Which-Trend-Is-Your-Friend)）：使用一些固定的回顾，你可以确定市场周期并捕捉到更多的上涨，从而提高绩效相对于买进并持有，或者至少改善回报与下跌风险之比。问题在于描述中的"固定"部分：我们所知道的市场是非平稳的，经济周期可以变化很大。
- en: In 2020, the COVID-19 selloff was unprecedented in its speed and ferocity relative
    to past corrections. The chart below from [“Towards Data Science”](https://towardsdatascience.com/understanding-the-2020-us-stock-market-drop-using-data-visualizations-bccd2d91bf9f)
    shows a comparison of the drawdown depth and number of days it took to get near
    the bottom.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '在2020年，COVID-19的抛售在速度和凶猛度上都空前，而且相对于以往的纠正来说。下面的来自[“Towards Data Science”](https://towardsdatascience.com/understanding-the-2020-us-stock-market-drop-using-data-visualizations-bccd2d91bf9f)的图表显示了回撤深度的对比和接近底部所需的天数。 '
- en: '[![](img/09d86b84769b0936e649233837fed23c.png)](https://cssanalytics.files.wordpress.com/2020/12/covid-drawdown.png)'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: '[![](img/09d86b84769b0936e649233837fed23c.png)](https://cssanalytics.files.wordpress.com/2020/12/covid-drawdown.png)'
- en: What you can also gather from the chart above is that corrections in 2015 and
    2018 were also relatively fast selloffs and that ***this may be a defining feature
    of the modern environment***. One can speculate rationally as to the cause of
    this situation; monetary policy driven asset bubbles via low interest rates that
    artificially inflate assets like balloons that expel quickly when the air is removed,
    and/or computerized trading that take advantage of sellers by moving prices rapidly
    away as pressure increases. Regardless of the reason, the reality is that markets
    seem to take the escalator up and the elevator down in today’s day and age. Traditional
    methods that rely on linear and static time-based lookbacks have been doing quite
    poorly which is not surprising. An article chronicling the struggles of trend-followers
    was posted on Bloomberg
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 从上面的图表中，你还可以得到的信息是，2015年和2018年的纠正也是相对较快的抛售，而***这可能是现代环境的一个决定性特征***。我们可以理性地推测造成这种情况的原因；通过低利率产生的货币政策驱动的资产泡沫，它会像气球一样被迅速排出空气而迅速消退，和/或者通过计算机化交易利用卖方在压力增大时迅速将价格快速移开。无论原因是什么，现实情况是，在今天这个时代，市场似乎是奔上楼梯，搭乘电梯下落。依赖线性和静态的基于时间的回顾的传统方法表现得相当糟糕，并不令人意外。《彭博》刊登了一篇关于趋势追踪者的挣扎的文章
- en: '[![](img/4cf9ad053ce307c25d39814f709a5d30.png)](https://cssanalytics.files.wordpress.com/2020/12/the-trend-isnt-always-your-friend.jpg)'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: '[![](img/4cf9ad053ce307c25d39814f709a5d30.png)](https://cssanalytics.files.wordpress.com/2020/12/the-trend-isnt-always-your-friend.jpg)'
- en: 'As you can see CTA’s have not been having an easy ride as of late and their
    struggles seemed to start around 2015\. I know what some of you are thinking:
    tactical long-only trend-following with ETFs is not the same as long/short hedge
    funds that trade futures. You are right and wrong: right in the sense that long
    only ETF has a tendency to profit from asset class positive drift, whereas long/short
    has no such favorable tailwinds especially with low interest rates. But wrong
    in the sense that this doesn’t discount the timing component of returns which
    has been unfavorable for equity indices. The problem is more straightforward when
    you consider how trend-following generates excess returns. In a fantastic [post
    by Philosophical Economics](http://www.philosophicaleconomics.com/2016/01/gtt/)
    he illustrates exactly what is responsible for trend-following P/L:'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 正如你所见，最近期内CTA并没有轻松的日子，并且他们的困难似乎起源于2015年。我知道你们中的一些人在想什么：仅战术的看多趋势跟随ETF并不同于交易期货的多空对冲基金。你们对和错：对，因为仅看多ETF有从资产类别正向漂移中获利的倾向，而多空对冲基金在低利率情况下没有这样有利的顺风。但是，错误在于这并不排除了预期收益的时机组成部分，而这对于股票指数并不利。当你考虑趋势跟随如何产生超额回报时，问题就更为直接了。在[哲学经济学的一篇绝妙的文章](http://www.philosophicaleconomics.com/2016/01/gtt/)中，他准确地说明了趋势跟随的盈亏责任所在：
- en: '[![](img/2bf97ffe9a5eaa9669eb5a776f22eafe.png)](https://cssanalytics.files.wordpress.com/2020/12/trend-following-math.jpg)'
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: '[![](img/2bf97ffe9a5eaa9669eb5a776f22eafe.png)](https://cssanalytics.files.wordpress.com/2020/12/trend-following-math.jpg)'
- en: The bottom line is that if markets are moving faster than the moving average
    oscillation period (roughly half the lookback) then you will lose money via whipsaw.
    This is made worse if the oscillation period is asymmetric such as when it takes
    longer to go up than down. Most trend-followers or tactical managers employ a
    1-year or 6-month lookback. These can be too long if the drawdown materializes
    within less than a quarter. Furthermore using holding periods that are monthly
    rather than daily inspection also introduces more luck into the equation since
    drawdowns can happen at any time rather than on someone’s desired rebalancing
    period. Savvy portfolio managers use multiple lookbacks and holding periods in
    order to reduce the variance associated with not knowing what the oscillation
    period will look like. ***However this does not address the core problem which
    requires a more dynamic or nonlinear approach***.
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: 总之，如果市场的波动速度快于移动平均振荡周期（大约是反观的一半），那么你会通过颠簸亏损。如果振荡周期是不对称的，比如上升需要的时间比下降长，那么情况会变得更糟。大多数趋势跟随者或战术管理者使用1年或6个月的反观。如果回撤发生在不到一个季度的时间内，那么这些期限可能太长了。此外，使用月度而不是每日检查的持有期也会在某种程度上引入更多的运气，因为回撤可能发生在任何时间，而不是在某人期望的再平衡时期。精明的组合管理者使用多重的反观和持有期，以减少与不知道振荡周期将是什么样子有关的方差。***然而，这并不解决需要更具动态或非线性方法的核心问题***。
- en: 'In a [recent paper by Garg et. al called “Momentum Turning Points”](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3489539)
    they explore the nature of dynamic trend-following or time-series momentum strategies.
    They call situations where short-term trends and long-term trends disagree to
    be “turning points” and the number of these turning points determine trend-following
    performance. [AllocateSmartly provides a fantastic post](https://allocatesmartly.com/momentum-turning-points/?aff=634)
    reviewing the paper and shows the following chart:'
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 在Garg等人最近的一篇题为“动量转折点”的论文中，他们探讨了动态趋势跟随或时间序列动量策略的性质。他们将短期趋势和长期趋势不一致的情况称为“转折点”，而这些转折点的数量决定了趋势跟随的表现。[AllocateSmartly提供了一篇绝妙的文章](https://allocatesmartly.com/momentum-turning-points/?aff=634)评论了这篇论文，并展示了以下图表：
- en: '[![](img/2e504c7b6c8037164c79eee2793ad844.png)](https://cssanalytics.files.wordpress.com/2020/12/impact-of-turning-points.png)'
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: '[![](img/2e504c7b6c8037164c79eee2793ad844.png)](https://cssanalytics.files.wordpress.com/2020/12/impact-of-turning-points.png)'
- en: '***A greater frequency of turning points is consistent with a faster oscillation
    as described by Philosophical Economics.*** As you can see when the number of
    turning points increases performance tends to decrease for traditional trend-following
    strategies which tend to rely on longer term and static lookbacks.'
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: '***更多的转折点频率与哲学经济学描述的更快振荡一致***。可以看到，当转折点的数量增加时，传统的趋势跟随策略的表现往往会下降，这些策略往往依赖于较长期和静态的反观。'
- en: 'Garg. et al in the paper classify different market states that result from
    short-term versus long-term trend-following signals:'
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: 在论文中，Garg等人对由短期与长期趋势跟踪信号产生的不同市场状态进行了分类：
- en: 'Bull: ST UP, LT UP'
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: 牛市：ST 上升，LT 上升
- en: 'Correction: ST DOWN, LT UP'
  id: totrans-19
  prefs: []
  type: TYPE_NORMAL
  zh: 修正：ST 下降，LT 上升
- en: 'Bear: ST DOWN, LT DOWN'
  id: totrans-20
  prefs: []
  type: TYPE_NORMAL
  zh: 熊市：ST 下降，LT 下降
- en: 'Rebound: ST UP, LT DOWN'
  id: totrans-21
  prefs: []
  type: TYPE_NORMAL
  zh: 反弹：ST 上升，LT 下降
- en: 'In reviewing optimal trend-following lookbacks as a function of market state
    the paper came up with an interesting conclusion:'
  id: totrans-22
  prefs: []
  type: TYPE_NORMAL
  zh: 在对市场状态的最佳趋势跟踪回溯进行审查时，这篇论文得出了一个有趣的结论：
- en: '“The conclusion from our state-dependent speed analysis: **elect slower-speed
    momentum after Correction months and faster-speed momentum after Rebound months**“'
  id: totrans-23
  prefs: []
  type: TYPE_NORMAL
  zh: “我们对于我们的状态依赖速度分析的结论：**在修正月份之后选择较慢速的动量，在反弹月份之后选择较快速的动量**“
- en: Unfortunately their solution to make such adjustments relies on longer-term
    optimization based on previous data. Even if this is walk-forward there is a considerable
    lag in the adjustment period. There is a simple way to account for oscillations
    that may occur more rapidly and potentially in a non-linear fashion. ***To state
    the obvious the concept of a “drawdown” is itself a nonlinear variable that is
    independent of time and is the most directly tied to investor profits*** which
    makes it a good candidate for making adjustments. Furthermore small drawdowns
    (corrections) based on the analysis presented in the paper above require longer
    lookbacks, while large drawdowns (that precede rebounds) require shorter/faster
    lookbacks. ***If we can use a relative measure of historical drawdowns within
    an adaptive framework this should more directly solve the problem.*** In this
    case we don’t care about how many turning points there are (which is the assumption
    made by choosing a static lookback) but rather how to adjust to them in a logical
    way.
  id: totrans-24
  prefs: []
  type: TYPE_NORMAL
  zh: 不幸的是，他们解决这种调整的方法依赖于基于先前数据的长期优化。即使是前瞻性优化，也存在调整周期中的可观滞后。有一种简单的方法可以解释可能更快地发生的振荡，可能是以非线性方式。***显而易见，"回撤"的概念本身是一个与时间无关的非线性变量，它最直接与投资者的利润挂钩***，因此它是调整的一个很好的选择。此外，根据上述论文中所呈现的分析，小回撤（修正）需要更长的回望，而较大的回撤（先前的反弹）则需要更短/更快的回望。***如果我们可以在自适应框架内使用历史回撤的相对度量，这应该更直接地解决问题。***在这种情况下，我们不关心有多少个拐点（这是选择静态回望的假设），而是如何以合乎逻辑的方式进行调整。
- en: '**The Simple Solution**'
  id: totrans-25
  prefs: []
  type: TYPE_NORMAL
  zh: '**简单解决方案**'
- en: 'The first step is to create a series of drawdowns from all-time highs (it isn’t
    critical to choose all-time, 1-year highs work well too). Then find the empirical
    distribution of such drawdowns using some lookback using a percentile ranking
    over the past 6 months (again not critical can use longer or shorter or a combination).
    I use the square of this value for the simple reason that we want to ignore small
    drawdowns and focus on larger drawdowns to make lookback length adjustments (remember
    corrections require long-term lookbacks and rebounds after large drawdowns require
    short-term lookbacks). Next choose a short-term trend-following lookback and a
    long-term lookback. In this case I chose 50 and 200 which are often followed by
    market participants via their respective moving averages but again the parameter
    choice is not critical. One practical point is that it is inefficient to use a
    really short-term lookback for tactical trading such as 20 days. We can calculate
    the optimal alpha of a moving average using the exponential moving average framework
    as follows:'
  id: totrans-26
  prefs: []
  type: TYPE_NORMAL
  zh: 第一步是从历史最高点创建一系列回撤（选择历史最高点并不是关键，1年最高点也很有效）。然后使用一些回溯数据在过去6个月的百分位排名，找出这些回撤的经验分布（再次强调并不是关键，可以使用更长或更短或组合）。我使用这个值的平方，原因很简单，我们想忽略小回撤，专注于较大回撤来进行回溯长度调整（必须记住，修正需要长期回溯，而大回撤后的反弹则需要短期回溯）。接下来选择一个短期趋势跟踪回溯和一个长期回溯。在这种情况下，我选择了50和200，这些经常被市场参与者通过各自的移动平均值关注，但参数选择并不重要。一个实际的观点是，在战术交易中使用真正短期的回溯（如20天）是低效的。我们可以使用指数移动平均法来计算移动平均值的最佳alpha值，如下：
- en: Percentile Ranking of Drawdowns ^ 2 (squared) = P
  id: totrans-27
  prefs: []
  type: TYPE_NORMAL
  zh: 回撤的百分位排名^2（平方）= P
- en: Short- Term Alpha= ST
  id: totrans-28
  prefs: []
  type: TYPE_NORMAL
  zh: 短期Alpha= ST
- en: Long-Term Alpha= LT
  id: totrans-29
  prefs: []
  type: TYPE_NORMAL
  zh: 长期Alpha= LT
- en: Optimal Alpha= P*ST+(1-P)*LT
  id: totrans-30
  prefs: []
  type: TYPE_NORMAL
  zh: 最佳Alpha= P*ST+(1-P)*LT
- en: 'We then calculate an adaptive moving average using the optimal alpha which
    looks like this:'
  id: totrans-31
  prefs: []
  type: TYPE_NORMAL
  zh: 然后我们使用最佳alpha计算自适应移动平均值，如下所示：
- en: '[![](img/e9a4d90cb88513ef832bc8640622c44a.png)](https://cssanalytics.files.wordpress.com/2020/12/adaptive-momentum-2.png)'
  id: totrans-32
  prefs: []
  type: TYPE_NORMAL
  zh: '[![](img/e9a4d90cb88513ef832bc8640622c44a.png)](https://cssanalytics.files.wordpress.com/2020/12/adaptive-momentum-2.png)'
- en: 'Notice that the adaptive moving average gets slower as the market makes new
    highs and faster after large drawdowns exactly as we would expect. The result
    is that it permits both earlier exits and entries into the market. The latter
    is far more important given the tendency for the market to make “V-shaped” recoveries.
    But to test this theory we need to backtest over a long time period and compare
    to traditional static lookbacks. Instead of using fixed holding periods we will
    do daily signal generation at the close. Since an adaptive moving average is not
    as effective as a simple moving average as a low pass filter it is important to
    filter the price when using a traditional price vs moving average strategy. To
    filter price I take the 10-day moving average of price (could be 3 could be 15
    doesn’t matter that much). Note that the price (or filtered price) vs moving average
    in an exponential moving average framework is mathematically equivalent to momentum.
    **Therefore using a price vs ema in this context is basically an adaptive momentum
    calculation.** Here is what Adaptive Momentum looks like vs typical static lookbacks:'
  id: totrans-33
  prefs: []
  type: TYPE_NORMAL
  zh: 注意，随着市场创出新高，自适应移动平均变慢，而在大幅回撤之后变快，这正如我们所预期的一样。其结果是，它允许更早地退出和进入市场。后者更为重要，因为市场倾向于进行“V型”恢复。但为了验证这个理论，我们需要在长时间段内进行回测，并与传统的静态回望进行比较。我们不使用固定的持仓期，而是在收盘时进行每日信号生成。由于自适应移动平均不像简单移动平均那样作为低通滤波器有效，所以在使用传统价格与移动平均策略时，对价格进行滤波是很重要的。我采用价格的10日移动平均（可以是3天也可以是15天，影响不大）。注意，在指数移动平均的框架中，价格（或经过滤波的价格）与移动平均相比在数学上是等效于动量的。**因此，在这种情况下使用价格与ema基本上就是一种自适应动量计算。**下面是自适应动量与典型的静态回望的对比：
- en: '[![](img/666570e8ff44bfb970a244bcc5199ed2.png)](https://cssanalytics.files.wordpress.com/2020/12/adpative-momentum-1.png)'
  id: totrans-34
  prefs: []
  type: TYPE_NORMAL
  zh: '[![](img/666570e8ff44bfb970a244bcc5199ed2.png)](https://cssanalytics.files.wordpress.com/2020/12/adpative-momentum-1.png)'
- en: 'And for the quants out there here is the performance table:'
  id: totrans-35
  prefs: []
  type: TYPE_NORMAL
  zh: 对于量化分析人员，下面是性能表：
- en: '[![](img/af73cd5ae719d7cbbe10bcdc690a273e.png)](https://cssanalytics.files.wordpress.com/2020/12/adaptive-table.png)'
  id: totrans-36
  prefs: []
  type: TYPE_NORMAL
  zh: '[![](img/af73cd5ae719d7cbbe10bcdc690a273e.png)](https://cssanalytics.files.wordpress.com/2020/12/adaptive-table.png)'
- en: Adaptive Momentum is the best performer in terms of CAGR, but most the biggest
    difference is in risk-adjusted returns (sharpe) and higher moments (skew and kurtosis).
    Adaptive Momentum has more positive skew and lower kurtosis indicating higher
    upside/downside capture and lower tail risk. What is most impressive is that it
    does so with nearly the same number of trades as 12-month time series momentum.
    If you look carefully at the line chart you can see that Adaptive Momentum does
    much better in recent years than the static lookbacks which we would expect. Overall
    performance is impressive and this can be considered as a practical approach for
    tactical asset allocation. An interesting note is that if you dispense with the
    percentile ranking in the calculation and simply increase the lookback to the
    maximum when the market is making new highs, and decrease the lookback to the
    minimum when the market is not making new highs you get pretty similar performance.
    Overall, the strategy doesn’t exhibit much parameter sensitivity at all.
  id: totrans-37
  prefs: []
  type: TYPE_NORMAL
  zh: 自适应动量在CAGR方面是表现最好的，但最大的差异在于风险调整后的回报（夏普比）和更高阶的矩（偏度和峰度）。自适应动量具有更多的正偏度和较低的峰度，表明上行/下行捕捉更高，尾部风险更低。最令人印象深刻的是，它几乎用与12个月时间序列动量相同数量的交易来实现这一点。如果你仔细看线图，你会发现自适应动量近年来表现比我们预期的静态回望要好得多。总体表现令人印象深刻，这可被视为一种实际的策略用于战术资产配置。有趣的是，如果在计算中取消百分位排名，并且简单地将回望延长到市场创出新高时的最大值，并在市场没有创出新高时将其减小，你会得到非常相似的表现。总的来说，这种策略几乎不表现出参数敏感性。
- en: While this simple solution is not a perfect approach, it certainly does make
    intuitive sense and produces worthwhile results. Given a choice between static
    and adaptive/dynamic I would personally take this type of approach for real-life
    trading.
  id: totrans-38
  prefs: []
  type: TYPE_NORMAL
  zh: 虽然这个简单的解决方案并不是完美的方法，但它确实具有直观的合理性，并且能产生有价值的结果。在静态和自适应/动态之间做选择的话，我个人会选择这种类型的方法进行实际交易。
