- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-18 06:48:17'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024年5月18日 06:48:17
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'HOXO-M - anonymous data analyst group in Japan - : Seamless analytical environment
    by WDI, dplyr, and rMaps'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: HOXO-M - 日本匿名数据分析团队 - ：WDI、dplyr和rMaps打造的无缝分析环境
- en: 来源：[http://mockquant.blogspot.com/2014/03/seamless-analytical-environment-by-wdi.html#0001-01-01](http://mockquant.blogspot.com/2014/03/seamless-analytical-environment-by-wdi.html#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[http://mockquant.blogspot.com/2014/03/seamless-analytical-environment-by-wdi.html#0001-01-01](http://mockquant.blogspot.com/2014/03/seamless-analytical-environment-by-wdi.html#0001-01-01)
- en: Recently I found that My R Guru [@ramnath_vaidya](https://twitter.com/ramnath_vaidya)
    is developping a new visualization package [rMaps](https://github.com/ramnathv/rMaps).
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 最近我发现我的R领域大师[@ramnath_vaidya](https://twitter.com/ramnath_vaidya)正在开发一个新的可视化包[rMaps](https://github.com/ramnathv/rMaps)。
- en: I was so excited when I saw it for the first time and I think that it's really
    awesome for plotting any data on a map.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 当我第一次看到它时，我感到非常兴奋，我认为在地图上绘制任何数据都非常棒。
- en: Let me explain how we can
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 让我解释一下我们如何
- en: Get data(WDI package)
  id: totrans-9
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 获取数据（WDI包）
- en: Manipulate data(dplyr package)
  id: totrans-10
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 操作数据（dplyr包）
- en: Visualize the result(rMaps package)
  id: totrans-11
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 用rMaps包可视化结果
- en: with greate R packages.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 用了很棒的R包。
- en: Except for rMaps package, you can install these packages(WDI, dplyr) from CRAN
    by usual way.
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: 除了rMaps包，你可以按照通常的方法从CRAN安装这些包（WDI、dplyr）。
- en: '[PRE0]'
  id: totrans-14
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: To install rMaps package, you just write the following commands on R console.
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: 要安装rMaps包，你只需要在R控制台上输入以下命令。
- en: '[PRE1]'
  id: totrans-16
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: (Don't forget to install “devtools” package to use install_github function.)
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: （不要忘记安装“devtools”包以使用install_github函数。）
- en: Now, as an example, I show you that
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: 现在，举个例子，我给你展示
- en: Get “CO2 emissions (kt)” data from World Bank by WDI package
  id: totrans-19
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 从世界银行用WDI包获取“二氧化碳排放（kt）”数据
- en: Summarze it to by dplyr package
  id: totrans-20
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 通过dplyr包对其进行总结
- en: Visualize it by rMaps package
  id: totrans-21
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 通过rMaps包可视化
- en: 'The result is shown below:'
  id: totrans-22
  prefs: []
  type: TYPE_NORMAL
  zh: 结果如下所示：
- en: …Enjoy!!!
  id: totrans-23
  prefs: []
  type: TYPE_NORMAL
  zh: …尽情享用！！！
- en: By the way, recently an Japanese R professional guy often posts his greate articles.
    I recommend you to see these articles if you are interested in visualizing and
    dplyr especially.
  id: totrans-24
  prefs: []
  type: TYPE_NORMAL
  zh: 顺便说一句，最近一个日本的R专业人士经常发布他的优秀文章。如果你对可视化和dplyr特别感兴趣，我建议你看看这些文章。
- en: 'Source codes:'
  id: totrans-25
  prefs: []
  type: TYPE_NORMAL
  zh: 源代码：
- en: '[PRE2]'
  id: totrans-26
  prefs: []
  type: TYPE_PRE
  zh: '[PRE2]'
