- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 06:48:17'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'HOXO-M - anonymous data analyst group in Japan - : Seamless analytical environment
    by WDI, dplyr, and rMaps'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[http://mockquant.blogspot.com/2014/03/seamless-analytical-environment-by-wdi.html#0001-01-01](http://mockquant.blogspot.com/2014/03/seamless-analytical-environment-by-wdi.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Recently I found that My R Guru [@ramnath_vaidya](https://twitter.com/ramnath_vaidya)
    is developping a new visualization package [rMaps](https://github.com/ramnathv/rMaps).
  prefs: []
  type: TYPE_NORMAL
- en: I was so excited when I saw it for the first time and I think that it's really
    awesome for plotting any data on a map.
  prefs: []
  type: TYPE_NORMAL
- en: Let me explain how we can
  prefs: []
  type: TYPE_NORMAL
- en: Get data(WDI package)
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Manipulate data(dplyr package)
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Visualize the result(rMaps package)
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: with greate R packages.
  prefs: []
  type: TYPE_NORMAL
- en: Except for rMaps package, you can install these packages(WDI, dplyr) from CRAN
    by usual way.
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
- en: To install rMaps package, you just write the following commands on R console.
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE1]'
  prefs: []
  type: TYPE_PRE
- en: (Don't forget to install “devtools” package to use install_github function.)
  prefs: []
  type: TYPE_NORMAL
- en: Now, as an example, I show you that
  prefs: []
  type: TYPE_NORMAL
- en: Get “CO2 emissions (kt)” data from World Bank by WDI package
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Summarze it to by dplyr package
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Visualize it by rMaps package
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'The result is shown below:'
  prefs: []
  type: TYPE_NORMAL
- en: …Enjoy!!!
  prefs: []
  type: TYPE_NORMAL
- en: By the way, recently an Japanese R professional guy often posts his greate articles.
    I recommend you to see these articles if you are interested in visualizing and
    dplyr especially.
  prefs: []
  type: TYPE_NORMAL
- en: 'Source codes:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE2]'
  prefs: []
  type: TYPE_PRE
