- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 04:43:32'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Humble Student of the Markets: How to cope in a low-return environment'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://humblestudentofthemarkets.blogspot.com/2010/07/how-to-cope-in-low-return-environment.html#0001-01-01](https://humblestudentofthemarkets.blogspot.com/2010/07/how-to-cope-in-low-return-environment.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: MarketWatch published an
  prefs: []
  type: TYPE_NORMAL
- en: '[article](http://www.marketwatch.com/story/market-timing-scores-with-tense-investors-2010-07-16)'
  prefs: []
  type: TYPE_NORMAL
- en: last week discussing the rise of trend based market timing strategies, compared
    to the more traditional buy-and-hold approach to investing. I also covered the
    same issue when I posted that we may have to
  prefs: []
  type: TYPE_NORMAL
- en: '[wait eight years for a new equity bull to begin](http://humblestudentofthemarkets.blogspot.com/2010/07/wait-8-years-for-new-bull.html)'
  prefs: []
  type: TYPE_NORMAL
- en: .
  prefs: []
  type: TYPE_NORMAL
- en: To recap, we may very well be in a secular bear market, where returns are roughly
    flat as illustrated by the chart of the DJIA below.
  prefs: []
  type: TYPE_NORMAL
- en: '**Zero return with portfolio volatility?**'
  prefs: []
  type: TYPE_NORMAL
- en: Let’s do a back of the envelope calculation. The stock market’s dividend yield
    is around 2% and the 10-year Treasuries yield around 3%. Assume that stocks have
    no capital appreciation over the next 5-10 years, the expectation of return of
    a buy-and-hold balanced fund is going to be around 2.5%, regardless how you play
    around with the asset mix decision.
  prefs: []
  type: TYPE_NORMAL
- en: Don't forget layer on the transaction costs and fees. After factoring in trading
    costs, which can easily be 1% or more for individuals, and investment management
    fees (conservatively estimated at 1-2% for an active solution, under 1% for passive
    solutions), the investor is left with little or nothing to show for his efforts,
    except for the volatility in his portfolio.
  prefs: []
  type: TYPE_NORMAL
- en: Why not just sock the money into a savings account?
  prefs: []
  type: TYPE_NORMAL
- en: '**Yield at a reasonable safety margin**'
  prefs: []
  type: TYPE_NORMAL
- en: To cope with a low return environment, the first-order solution for the buy-and-hold
    crowd has been to seek out yield. But there is no free lunch here either. Higher
    yield comes at the price of credit risk and credit risk could blow up in our faces
    in the current fragile economic environment. Some investment managers have sought
    to mitigate that with the concept of yield at a reasonable safety margin, which
    is not a bad solution under the circumstances and the constraints of a fixed asset
    allocation.
  prefs: []
  type: TYPE_NORMAL
- en: '**Dynamic asset allocation using trend following principles**'
  prefs: []
  type: TYPE_NORMAL
- en: My solution, along with some others cited in the
  prefs: []
  type: TYPE_NORMAL
- en: '[MarketWatch article](http://www.marketwatch.com/story/market-timing-scores-with-tense-investors-2010-07-16)'
  prefs: []
  type: TYPE_NORMAL
- en: ', is to trade the swings. The swings can be considerable – witness the trough-to-peak
    behavior of stocks since the March 2009 bottom.'
  prefs: []
  type: TYPE_NORMAL
- en: I am not alone in my choice of modeling platform. My
  prefs: []
  type: TYPE_NORMAL
- en: '[Inflation-Deflation Timer model](http://www.qwestfunds.com/publications/newsletters_pdf/newsletter_november_2009.pdf)'
  prefs: []
  type: TYPE_NORMAL
- en: is based on trend following principles, as applied to various commodity prices.
    The MarketWatch article cites others who use similar techniques.
  prefs: []
  type: TYPE_NORMAL
- en: '[Mebane Faber](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=962461)'
  prefs: []
  type: TYPE_NORMAL
- en: uses similar kinds of principles to limit losses in asset allocation.
  prefs: []
  type: TYPE_NORMAL
- en: Coping with a low return environment is hard. Preserving financial staying power
    is of paramount importance under these circumstances. For those who believe in
    the static buy-and-hold asset allocation approach to investing, reaching for yield
    as a source of stability can be a reasonable approach if credit analysis is done
    properly. I happen to be in the dynamic asset allocation camp, where I believe
    the returns can be considerably higher given the likely volatility of the financial
    markets.
  prefs: []
  type: TYPE_NORMAL
