- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-18 01:10:14'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 01:10:14
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Humble Student of the Markets: A decade-long low return environment for equities?'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 谦卑的市场学生：股票市场是否将面临长达十年的低回报环境？
- en: 来源：[https://humblestudentofthemarkets.blogspot.com/2008/05/decade-long-low-return-environment-for.html#0001-01-01](https://humblestudentofthemarkets.blogspot.com/2008/05/decade-long-low-return-environment-for.html#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://humblestudentofthemarkets.blogspot.com/2008/05/decade-long-low-return-environment-for.html#0001-01-01](https://humblestudentofthemarkets.blogspot.com/2008/05/decade-long-low-return-environment-for.html#0001-01-01)
- en: The chart below shows the Dow Jones Industrials Average from 1947 to the present.
    This brief history of the Dow has been marked by two eras of rallying markets,
    followed by a long sideways market. We could be moving into another period of
    sideways markets for another decade or so.
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 下图展示了道琼斯工业平均指数从1947年至今的情况。道琼斯的这段简短历史以两个看涨市场的时代为标志，随后是长期的横盘市场。我们可能正进入另一个长达十年的横盘市场时期。
- en: '[![](img/82be9f37affcca4122c24c3b9c4e6cf1.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgo36-OTP3Ahehslp1P-NG31uJBtw57PSPcfPo8wOhrhPO3BSC4pK2ww-fbHnT-VzIthR8mcf-DQfDm8oyYrEOzrUShJoiOUE25FFVGjtPdPte62mlXduNS53c9wFVH0EtfEEtbbRCnxuYV/s1600-h/DJIA.JPG)**Poor
    macro-economic backdrop**'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '![宏观经济背景](img/82be9f37affcca4122c24c3b9c4e6cf1.png)的恐慌故事）[点击查看](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgo36-OTP3Ahehslp1P-NG31uJBtw57PSPcfPo8wOhrhPO3BSC4pK2ww-fbHnT-VzIthR8mcf-DQfDm8oyYrEOzrUShJoiOUE25FFVGjtPdPte62mlXduNS53c9wFVH0EtfEEtbbRCnxuYV/s1600-h/DJIA.JPG)**宏观经济背景**'
- en: There are valid fundamental reasons for these sideways markets. The last sideways
    pattern has been marked by rising inflationary expectations that begun with LBJ’s
    guns and butter policy in the Vietnam War. The macro-economic backdrop is not
    dissimilar to that of the late 1960s and 1970s. America is involved in a war with
    no end in sight, the fiscal deficit is spiraling out of control and the US Dollar
    is falling.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 这些横盘市场有合理的根本原因。上一个横盘模式以不断上升的通货膨胀预期为标志，这种预期始于越南战争时期LBJ的“枪支和黄油”政策。宏观经济背景与20世纪60年代后期和70年代相似。美国卷入了一场看不到尽头的战争，财政赤字失控，美元贬值。
- en: '**Excessive equity valuations**'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: '**过度的股票估值**'
- en: Some investors, like John Hussman, believe that the market is excessively priced.
    In a recent
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 一些投资者，比如约翰· Hussman，认为市场定价过高。在最近
- en: '[commentary](http://www.hussmanfunds.com/wmc/wmc080505.htm)'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: '[评论](http://www.hussmanfunds.com/wmc/wmc080505.htm)'
- en: he wrote that “the S&P 500 remains priced to deliver probable total returns
    of about 2-4% annually over the coming decade”. Using the
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 他写道：“标普500指数在未来十年内预计每年的总回报率大约为2-4%”。使用
- en: '[methodology](http://www.hussmanfunds.com/wmc/wmc050222.htm)'
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: '[方法论](http://www.hussmanfunds.com/wmc/wmc050222.htm)'
- en: described here, Hussman indicates that the market’s cyclically adjusted P/E
    based on peak earnings is very high. Profit margins are elevated at this point
    of the cycle and there is the market is not pricing in any room for margin mean
    reversion (read analysis
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 描述中，Hussman指出，基于峰值收益的市场的周期性调整市盈率非常高。当前周期的利润率处于高位，市场没有为利润率均值回归留出空间（阅读分析）。
- en: '[here](http://hussmanfunds.com/rsi/profitmargins.htm)'
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: '[这里](http://hussmanfunds.com/rsi/profitmargins.htm)'
- en: ).
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: ）。
- en: '**Pension funds asset mixes likely to favor more bonds**'
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: '**养老金资产组合可能更青睐债券**'
- en: Corporate treasurers are likely to move towards a asset-liability matching framework
    in defined benefits plans given the advent of changes in accounting policy such
    as
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: 企业财务主管可能会在定义利益计划中转向资产和负债匹配的框架，鉴于会计政策的变化，如
- en: '[FASB 158](http://www.fasb.org/pdf/fas158.pdf)'
  id: totrans-19
  prefs: []
  type: TYPE_NORMAL
  zh: '[FASB 158](http://www.fasb.org/pdf/fas158.pdf)'
- en: and
  id: totrans-20
  prefs: []
  type: TYPE_NORMAL
  zh: 以及
- en: '[IAS 19](http://www.iasplus.com/standard/ias19.htm)'
  id: totrans-21
  prefs: []
  type: TYPE_NORMAL
  zh: '[IAS 19](http://www.iasplus.com/standard/ias19.htm)'
- en: . In Europe there are already suggestions to extend the
  id: totrans-22
  prefs: []
  type: TYPE_NORMAL
  zh: 。在欧洲，已有建议延长
- en: '[Solvency II standard](http://pensions.practicallaw.com/8-368-6956)'
  id: totrans-23
  prefs: []
  type: TYPE_NORMAL
  zh: '[偿付能力II标准](http://pensions.practicallaw.com/8-368-6956)'
- en: to corporate pension plans, which would further accelerate this trend (and has
    created scare stories like
  id: totrans-24
  prefs: []
  type: TYPE_NORMAL
  zh: 对于企业养老金计划，这将进一步加速这一趋势（并已经制造了类似
- en: '[this](http://www.reuters.com/article/privateEquity/idUSL0616178620080506?pageNumber=1&virtualBrandChannel=0)'
  id: totrans-25
  prefs: []
  type: TYPE_NORMAL
  zh: '[这个](http://www.reuters.com/article/privateEquity/idUSL0616178620080506?pageNumber=1&virtualBrandChannel=0)'
- en: ).
  id: totrans-26
  prefs: []
  type: TYPE_NORMAL
  zh: ）。
- en: We saw this effect in the UK a few years ago when companies moved towards an
    asset-liability matching framework. Investors drove the yield on the long-dated
    gilt to unbelievably low levels as they reached for duration in their portfolios.
    This asset shift came at the expense of equity weightings and other assets in
    the pension portfolio.
  id: totrans-27
  prefs: []
  type: TYPE_NORMAL
  zh: 我们在几年前英国的公司向资产负债匹配框架转变时看到了这种效应。投资者为了延长投资组合的久期，将长期国债收益率压至难以置信的低位。这种资产转换是以牺牲养老金投资组合中的股票权重和其他资产为代价的。
