- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 01:49:35'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Humble Student of the Markets: A "penny wise, pound foolish" application of
    the Trend Model'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://humblestudentofthemarkets.blogspot.com/2022/01/a-penny-wise-pound-foolish-application.html#0001-01-01](https://humblestudentofthemarkets.blogspot.com/2022/01/a-penny-wise-pound-foolish-application.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: I received a number of responses to the post on
  prefs: []
  type: TYPE_NORMAL
- en: '[the 2021 report card](https://humblestudentofthemarkets.com/2021/12/27/a-2021-report-card/)'
  prefs: []
  type: TYPE_NORMAL
- en: on my investment models. While most were complimentary, one reader asked me
    for a more aggressive formulation of the Trend Asset Allocation Model.
  prefs: []
  type: TYPE_NORMAL
- en: As a reminder, the signals of the Trend Model are out-of-sample signals, but
    there are no portfolio returns to publish, mainly because I don't know anything
    about you. I know nothing about your return targets, your risk tolerance and pain
    thresholds, your tax situation, or even the jurisdiction you are in. If I offered
    an actual portfolio, it would be a formal prospectus document outlining what to
    expect.
  prefs: []
  type: TYPE_NORMAL
- en: Instead, the backtested returns are based on a specific formula for constructing
    a balanced fund portfolio based on Trend Model scores and reasonable risk assumptions
    of an average investor with a 60% stock/40% bond asset allocation.
  prefs: []
  type: TYPE_NORMAL
- en: 'Risk-on: 80% SPY (S&P 500), 20% IEF (7-10 Treasuries)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Neutral: 60% SPY, 40% IEF'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Risk-off: 40% SPY, 60% IEF'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: An advisor or portfolio manager could then change the equity allocation by 20%
    depending on the Trend Model score without Compliance tapping him on the shoulder.
  prefs: []
  type: TYPE_NORMAL
- en: The historical backtest of the Trend Model using this portfolio construction
    technique yielded excellent results. An investor using this approach could achieve
    equity-like returns while bearing balanced fund-like risk. Needless to say, this
    backtest is just a proof of concept. Every investor is different and your mileage
    will vary.
  prefs: []
  type: TYPE_NORMAL
- en: A reader then asked me to backtest a more aggressive approach to portfolio construction.
    Instead of a 60% SPY and 40% IEF benchmark, he suggested a 100% equity position,
    based on 60% SPY and 40% defensive equity substitute for bonds. The defensive
    portfolio consists of an equal-weighted portfolio of XLV (Healthcare), XLP (Consumer
    Staples), XLU (Utilities), and XLRE (Real Estate).
  prefs: []
  type: TYPE_NORMAL
- en: The results turned out to be a case of "penny wise, pound foolish".
  prefs: []
  type: TYPE_NORMAL
- en: The full post can be found
  prefs: []
  type: TYPE_NORMAL
- en: '[here](https://humblestudentofthemarkets.com/2022/01/03/a-penny-wise-pound-foolish-application-of-the-trend-model/)'
  prefs: []
  type: TYPE_NORMAL
- en: .
  prefs: []
  type: TYPE_NORMAL
