- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 01:10:14'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Humble Student of the Markets: A decade-long low return environment for equities?'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://humblestudentofthemarkets.blogspot.com/2008/05/decade-long-low-return-environment-for.html#0001-01-01](https://humblestudentofthemarkets.blogspot.com/2008/05/decade-long-low-return-environment-for.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: The chart below shows the Dow Jones Industrials Average from 1947 to the present.
    This brief history of the Dow has been marked by two eras of rallying markets,
    followed by a long sideways market. We could be moving into another period of
    sideways markets for another decade or so.
  prefs: []
  type: TYPE_NORMAL
- en: '[![](img/82be9f37affcca4122c24c3b9c4e6cf1.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgo36-OTP3Ahehslp1P-NG31uJBtw57PSPcfPo8wOhrhPO3BSC4pK2ww-fbHnT-VzIthR8mcf-DQfDm8oyYrEOzrUShJoiOUE25FFVGjtPdPte62mlXduNS53c9wFVH0EtfEEtbbRCnxuYV/s1600-h/DJIA.JPG)**Poor
    macro-economic backdrop**'
  prefs: []
  type: TYPE_NORMAL
- en: There are valid fundamental reasons for these sideways markets. The last sideways
    pattern has been marked by rising inflationary expectations that begun with LBJ’s
    guns and butter policy in the Vietnam War. The macro-economic backdrop is not
    dissimilar to that of the late 1960s and 1970s. America is involved in a war with
    no end in sight, the fiscal deficit is spiraling out of control and the US Dollar
    is falling.
  prefs: []
  type: TYPE_NORMAL
- en: '**Excessive equity valuations**'
  prefs: []
  type: TYPE_NORMAL
- en: Some investors, like John Hussman, believe that the market is excessively priced.
    In a recent
  prefs: []
  type: TYPE_NORMAL
- en: '[commentary](http://www.hussmanfunds.com/wmc/wmc080505.htm)'
  prefs: []
  type: TYPE_NORMAL
- en: he wrote that “the S&P 500 remains priced to deliver probable total returns
    of about 2-4% annually over the coming decade”. Using the
  prefs: []
  type: TYPE_NORMAL
- en: '[methodology](http://www.hussmanfunds.com/wmc/wmc050222.htm)'
  prefs: []
  type: TYPE_NORMAL
- en: described here, Hussman indicates that the market’s cyclically adjusted P/E
    based on peak earnings is very high. Profit margins are elevated at this point
    of the cycle and there is the market is not pricing in any room for margin mean
    reversion (read analysis
  prefs: []
  type: TYPE_NORMAL
- en: '[here](http://hussmanfunds.com/rsi/profitmargins.htm)'
  prefs: []
  type: TYPE_NORMAL
- en: ).
  prefs: []
  type: TYPE_NORMAL
- en: '**Pension funds asset mixes likely to favor more bonds**'
  prefs: []
  type: TYPE_NORMAL
- en: Corporate treasurers are likely to move towards a asset-liability matching framework
    in defined benefits plans given the advent of changes in accounting policy such
    as
  prefs: []
  type: TYPE_NORMAL
- en: '[FASB 158](http://www.fasb.org/pdf/fas158.pdf)'
  prefs: []
  type: TYPE_NORMAL
- en: and
  prefs: []
  type: TYPE_NORMAL
- en: '[IAS 19](http://www.iasplus.com/standard/ias19.htm)'
  prefs: []
  type: TYPE_NORMAL
- en: . In Europe there are already suggestions to extend the
  prefs: []
  type: TYPE_NORMAL
- en: '[Solvency II standard](http://pensions.practicallaw.com/8-368-6956)'
  prefs: []
  type: TYPE_NORMAL
- en: to corporate pension plans, which would further accelerate this trend (and has
    created scare stories like
  prefs: []
  type: TYPE_NORMAL
- en: '[this](http://www.reuters.com/article/privateEquity/idUSL0616178620080506?pageNumber=1&virtualBrandChannel=0)'
  prefs: []
  type: TYPE_NORMAL
- en: ).
  prefs: []
  type: TYPE_NORMAL
- en: We saw this effect in the UK a few years ago when companies moved towards an
    asset-liability matching framework. Investors drove the yield on the long-dated
    gilt to unbelievably low levels as they reached for duration in their portfolios.
    This asset shift came at the expense of equity weightings and other assets in
    the pension portfolio.
  prefs: []
  type: TYPE_NORMAL
