- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-18 04:47:02'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 04:47:02
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Intelligent Trading: Artificial Immune Systems and Financial Applications?'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 智能交易：人工免疫系统与金融应用？
- en: 来源：[http://intelligenttradingtech.blogspot.com/2010/02/artificial-immune-systems-and-financial.html#0001-01-01](http://intelligenttradingtech.blogspot.com/2010/02/artificial-immune-systems-and-financial.html#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[http://intelligenttradingtech.blogspot.com/2010/02/artificial-immune-systems-and-financial.html#0001-01-01](http://intelligenttradingtech.blogspot.com/2010/02/artificial-immune-systems-and-financial.html#0001-01-01)
- en: One of the buzzwords that seems to be common these days is AIS or Artificial
    Immune Systems. It is a biologically inspired classification type system that
    essentially tries to replicate some of our own natural immune system algorithms.
    Our bodies have various defense mechanisms for recognizing foreign invaders. One
    such defense mechanism is utilizing pathogen-associated molecular patterns built
    into our genome so that we can identify foreign pathogens and respond to them.
    This concept of being able to distinguish between self and non-self is essentially
    one of the main themes that is borrowed from our natural biological defense.
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 目前流行的一个术语是AIS或人工免疫系统。它是一种本质上试图复制我们自身天然免疫系统算法的生物启发分类系统。我们的身体有各种识别外来入侵者的防御机制。其中一种防御机制是利用构建在我们基因组中的病原体相关分子模式，这样我们就可以识别外来病原体并对其做出反应。这种能够区分自我和非自我的概念，实际上是从我们的天然生物防御中借鉴的一个主要主题。
- en: The idea is that we can learn to recognize objects that are not normal and respond
    to them. A good example where this has been put to use is in SPAM detection. We
    want to be able to recognize good (known) mail from the (unknown) bad, and utilize
    AIS to avoid parasitic SPAM.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 这个想法是我们可以学会识别不正常的物体并对它们做出反应。一个很好的例子是SPAM检测。我们希望能够识别出好的（已知的）邮件和（未知的）坏的邮件，并利用AIS避免寄生SPAM。
- en: The most common AIS system that has been adopted is the Negative Selection Algorithm.
    It essentially works by training a classifier to generate negative examples randomly
    and if the negative example (imagine a coordinate on a 2D grid) happens to be
    located (using some distance metric, such as euclidean or mahanalobis distance)
    near enough to a known good example, then it is rejected. Essentially, we are
    randomly generating negative examples for the classifier to identify.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 目前最常用的AIS系统是负选择算法。它本质上是通过训练分类器生成负样本随机，如果这个负样本（想象一个2D网格上的坐标）随机生成的位置（使用一些距离度量，如欧几里得或马哈拉诺比斯距离）靠近一个已知的好的例子，那么它就被拒绝。本质上，我们是为分类器随机生成负样本。
- en: '[![](img/39d918c3e32cf7aa268b6c1e1a8b4849.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi1co2vpaA80sKbC4xCRF0Elj3FQY5V-_WmlCg6G0JgYdAawwoe-ARahpfVBoFXIOyYuaHRM8vousbGSAra5cou9o7ZErX3owcj9qbJDgJWahw2ua5CB2oGwjitSXnk5lx13PODK05bRgI/s1600-h/AIS_example.jpg)'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: '![图](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi1co2vpaA80sKbC4xCRF0Elj3FQY5V-_WmlCg6G0JgYdAawwoe-ARahpfVBoFXIOyYuaHRM8vousbGSAra5cou9o7ZErX3owcj9qbJDgJWahw2ua5CB2oGwjitSXnk5lx13PODK05bRgI/s1600-h/AIS_example.jpg)'
- en: Fig 1\. Basic concept of AIS type classification
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 图1. AIS类型分类的基本概念
- en: Although it has been used in some cases for applications like credit detection,
    one of the things you'll notice in AI based algorithms is that there are many
    other algorithms that might do the same job or better. In the case of trading
    systems, we might want to identify abnormal time series behavior and make a decision
    based upon this information, however, it is might be simpler to use statistical
    control methods to better ascertain the information.
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 虽然它已经在一些信用检测等应用中被使用，但在基于AI的算法中，你会发现还有很多其他算法可能做同样的工作或更好。在交易系统中，我们可能想要识别异常的时间序列行为并根据这些信息做出决策，然而，使用统计控制方法可能更容易确定这些信息。
- en: In conclusion, although the idea sounds promising, I haven't seen many practical
    superior examples that would benefit a trading system that cannot be employed
    by existing AI algorithms.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 总之，尽管这个想法听起来很有希望，但我还没有看到很多实践中的优秀例子，这些例子对于交易系统来说无法通过现有的AI算法来实现。
- en: '[artificial immmune systems](http://www.artificial-immune-systems.org/)'
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: '[人工免疫系统](http://www.artificial-immune-systems.org/)'
- en: There is a wealth of good reading in the linked site, as well as a Weka plugin
    that can be used to access this algorithm for readers following the Weka tutorials.
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 该网站上有很多优秀的阅读材料，还有一个Weka插件，可以供跟随Weka教程的读者使用此算法。
