- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-18 06:37:18'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 06:37:18
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: iOS Linked-In Hybrid Applications | Tales from a Trading Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: iOS LinkedIn 混合应用 | 交易桌上的故事
- en: 来源：[https://mdavey.wordpress.com/2012/07/17/ios-linked-in-hybrid-applications/#0001-01-01](https://mdavey.wordpress.com/2012/07/17/ios-linked-in-hybrid-applications/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://mdavey.wordpress.com/2012/07/17/ios-linked-in-hybrid-applications/#0001-01-01](https://mdavey.wordpress.com/2012/07/17/ios-linked-in-hybrid-applications/#0001-01-01)
- en: iOS Linked-In Hybrid Applications
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: iOS LinkedIn 混合应用
- en: '[HTML5 Lessons from LinkedIn using Node.js](http://www.eventnook.com/video/v/360/HTML5-Lessons-from-LinkedIn-using-Nodejs)
    provides details of the Linked-In hybrid iOS applications from 36 mins into the
    video.  Interesting that Linked-In is moving more code to HTML5 on the iOS from
    its original native/HTML split.'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '[HTML5 从 LinkedIn 学习 Node.js 应用](http://www.eventnook.com/video/v/360/HTML5-Lessons-from-LinkedIn-using-Nodejs)
    视频从 36 分钟开始详细介绍了 LinkedIn 的 iOS 混合应用。有趣的是，LinkedIn 正在将其更多代码从原有的原生/HTML 混合模式转移到
    iOS 的 HTML5。'
- en: ~ by mdavey on July 17, 2012.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 作者：mdavey 发表于 July 17, 2012。
- en: Posted in [Uncategorized](https://mdavey.wordpress.com/category/uncategorized/)
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 发表于 [未分类](https://mdavey.wordpress.com/category/uncategorized/)
