- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 06:37:18'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: iOS Linked-In Hybrid Applications | Tales from a Trading Desk
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://mdavey.wordpress.com/2012/07/17/ios-linked-in-hybrid-applications/#0001-01-01](https://mdavey.wordpress.com/2012/07/17/ios-linked-in-hybrid-applications/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: iOS Linked-In Hybrid Applications
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: '[HTML5 Lessons from LinkedIn using Node.js](http://www.eventnook.com/video/v/360/HTML5-Lessons-from-LinkedIn-using-Nodejs)
    provides details of the Linked-In hybrid iOS applications from 36 mins into the
    video.  Interesting that Linked-In is moving more code to HTML5 on the iOS from
    its original native/HTML split.'
  prefs: []
  type: TYPE_NORMAL
- en: ~ by mdavey on July 17, 2012.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [Uncategorized](https://mdavey.wordpress.com/category/uncategorized/)
  prefs: []
  type: TYPE_NORMAL
