- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 04:57:30'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Magmasystems Blog: Reuters Config Files - Where do they go?'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[http://magmasystems.blogspot.com/2008/11/reuters-config-files-where-do-they-go.html#0001-01-01](http://magmasystems.blogspot.com/2008/11/reuters-config-files-where-do-they-go.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: If you are using the Reuters RFA 6.x APIs to consume market data, you know that
    there are three config files that RFA needs to find. These configuration files
    are
  prefs: []
  type: TYPE_NORMAL
- en: RFA.CFG
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: appendix_a
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: enumtype.def
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Usually, if you are running a console or WinForms application, you put these
    config files in the same directory as your executable.
  prefs: []
  type: TYPE_NORMAL
- en: However, what if you are running a
  prefs: []
  type: TYPE_NORMAL
- en: Windows Service
  prefs: []
  type: TYPE_NORMAL
- en: that uses RFA?
  prefs: []
  type: TYPE_NORMAL
- en: 'After some experimentation, we found that you need to store the files in these
    places:'
  prefs: []
  type: TYPE_NORMAL
- en: Windows 32 - Put the files in c:\WINNT\system32
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Windows 64 - Put the files in c:\WINNT\SysWow64
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: A service or an executable that uses RFA (the Marketfeed API, not the OMM API)
    uses 32-bit DLLs. This is because Reuters does not yet have 64-bit DLLs for RFA.
    Therefore, you need to use
  prefs: []
  type: TYPE_NORMAL
- en: '[CorFlags.exe](http://msdn.microsoft.com/en-us/library/ms164699%28VS.80%29.aspx)'
  prefs: []
  type: TYPE_NORMAL
- en: on a 64-bit Windows 2003 server in order to get your application to run.
  prefs: []
  type: TYPE_NORMAL
- en: Thanks to the wonderful Procmon utility from SysInternals for helping us out
    with this issue.
  prefs: []
  type: TYPE_NORMAL
- en: ©2008 Marc Adler - All Rights Reserved.
  prefs: []
  type: TYPE_NORMAL
- en: All opinions here are personal, and have no relation to my employer.
  prefs: []
  type: TYPE_NORMAL
