- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-18 04:57:30'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-18 04:57:30'
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Magmasystems Blog: Reuters Config Files - Where do they go?'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: Magmasystems 博客：路透社配置文件 - 它们去了哪里？
- en: 来源：[http://magmasystems.blogspot.com/2008/11/reuters-config-files-where-do-they-go.html#0001-01-01](http://magmasystems.blogspot.com/2008/11/reuters-config-files-where-do-they-go.html#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[http://magmasystems.blogspot.com/2008/11/reuters-config-files-where-do-they-go.html#0001-01-01](http://magmasystems.blogspot.com/2008/11/reuters-config-files-where-do-they-go.html#0001-01-01)
- en: If you are using the Reuters RFA 6.x APIs to consume market data, you know that
    there are three config files that RFA needs to find. These configuration files
    are
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 如果您正在使用路透社 RFA 6.x API 消费市场数据，您知道 RFA 需要找到三个配置文件。这些配置文件是
- en: RFA.CFG
  id: totrans-7
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: RFA.CFG
- en: appendix_a
  id: totrans-8
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: appendix_a
- en: enumtype.def
  id: totrans-9
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: enumtype.def
- en: Usually, if you are running a console or WinForms application, you put these
    config files in the same directory as your executable.
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 通常，如果您正在运行控制台或 WinForms 应用程序，您将这些配置文件放在可执行文件的同一目录中。
- en: However, what if you are running a
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 但是，如果您正在运行一个
- en: Windows Service
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: Windows 服务
- en: that uses RFA?
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: 使用了 RFA 的服务或可执行文件？
- en: 'After some experimentation, we found that you need to store the files in these
    places:'
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 经过一些实验，我们发现您需要将文件存储在这些位置：
- en: Windows 32 - Put the files in c:\WINNT\system32
  id: totrans-15
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Windows 32 - 将文件放在 c:\WINNT\system32
- en: Windows 64 - Put the files in c:\WINNT\SysWow64
  id: totrans-16
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Windows 64 - 将文件放在 c:\WINNT\SysWow64
- en: A service or an executable that uses RFA (the Marketfeed API, not the OMM API)
    uses 32-bit DLLs. This is because Reuters does not yet have 64-bit DLLs for RFA.
    Therefore, you need to use
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: 使用 RFA 的服务或可执行文件（市场数据 API，而不是 OMM API）使用 32 位 DLL。这是因为路透社还没有为 RFA 提供 64 位 DLL。因此，您需要使用
- en: '[CorFlags.exe](http://msdn.microsoft.com/en-us/library/ms164699%28VS.80%29.aspx)'
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: '[CorFlags.exe](http://msdn.microsoft.com/en-us/library/ms164699%28VS.80%29.aspx)'
- en: on a 64-bit Windows 2003 server in order to get your application to run.
  id: totrans-19
  prefs: []
  type: TYPE_NORMAL
  zh: 在 64位的 Windows 2003 服务器上运行，以便使您的应用程序运行。
- en: Thanks to the wonderful Procmon utility from SysInternals for helping us out
    with this issue.
  id: totrans-20
  prefs: []
  type: TYPE_NORMAL
  zh: 感谢 SysInternals 提供的 wonderful Procmon 工具，它帮助我们解决了这个问题。
- en: ©2008 Marc Adler - All Rights Reserved.
  id: totrans-21
  prefs: []
  type: TYPE_NORMAL
  zh: ©2008 Marc Adler - 版权所有。
- en: All opinions here are personal, and have no relation to my employer.
  id: totrans-22
  prefs: []
  type: TYPE_NORMAL
  zh: 这里的所有观点都是个人的，与我的雇主无关。
