- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 05:37:23'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Neo4j Full Stack Applications | Tales from a Trading Desk
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://mdavey.wordpress.com/2015/12/02/neo4j-full-stack-applications/#0001-01-01](https://mdavey.wordpress.com/2015/12/02/neo4j-full-stack-applications/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Neo4j Full Stack Applications
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: 'Great [presentation](https://skillsmatter.com/skillscasts/7098-neo4j-full-stack-applications-lessons-and-disasters-from-the-field)
    from Matt on using Neo4j “Lessons and Disasters from the field”. Callouts:'
  prefs: []
  type: TYPE_NORMAL
- en: Graph [Databases](http://neo4j.com/books/graph-databases/)
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Networks, Crowds, and [Markets](http://www.amazon.co.uk/Networks-Crowds-Markets-Reasoning-Connected/dp/0521195330):
    Reasoning About a Highly Connected World'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Be careful of properties on relationships
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Thoughts on [building](http://stitched.io/posts/2015-05-06-neo4j-full-stack/)
    Neo4j-based full-stack applications
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Performance – avoid part_of relationships, managed extensions REQUIRED – Java
    graph logic!
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Versioning is hard
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: ElasticSearch
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: ~ by mdavey on December 2, 2015.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [Languages](https://mdavey.wordpress.com/category/languages/)
  prefs: []
  type: TYPE_NORMAL
