- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-18 05:37:23'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 05:37:23
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Neo4j Full Stack Applications | Tales from a Trading Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: Neo4j全栈应用 | 交易桌面故事
- en: 来源：[https://mdavey.wordpress.com/2015/12/02/neo4j-full-stack-applications/#0001-01-01](https://mdavey.wordpress.com/2015/12/02/neo4j-full-stack-applications/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://mdavey.wordpress.com/2015/12/02/neo4j-full-stack-applications/#0001-01-01](https://mdavey.wordpress.com/2015/12/02/neo4j-full-stack-applications/#0001-01-01)
- en: Neo4j Full Stack Applications
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: Neo4j全栈应用
- en: 'Great [presentation](https://skillsmatter.com/skillscasts/7098-neo4j-full-stack-applications-lessons-and-disasters-from-the-field)
    from Matt on using Neo4j “Lessons and Disasters from the field”. Callouts:'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 来自Matt的[精彩演讲](https://skillsmatter.com/skillscasts/7098-neo4j-full-stack-applications-lessons-and-disasters-from-the-field)，讲述了使用Neo4j的“经验和灾难”。注意点：
- en: Graph [Databases](http://neo4j.com/books/graph-databases/)
  id: totrans-8
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 图[数据库](http://neo4j.com/books/graph-databases/)
- en: 'Networks, Crowds, and [Markets](http://www.amazon.co.uk/Networks-Crowds-Markets-Reasoning-Connected/dp/0521195330):
    Reasoning About a Highly Connected World'
  id: totrans-9
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 网络、群体与[市场](http://www.amazon.co.uk/Networks-Crowds-Markets-Reasoning-Connected/dp/0521195330)：关于一个高度互联世界的推理
- en: Be careful of properties on relationships
  id: totrans-10
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 小心关系上的属性
- en: Thoughts on [building](http://stitched.io/posts/2015-05-06-neo4j-full-stack/)
    Neo4j-based full-stack applications
  id: totrans-11
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 关于[构建](http://stitched.io/posts/2015-05-06-neo4j-full-stack/)基于Neo4j的全栈应用的思考
- en: Performance – avoid part_of relationships, managed extensions REQUIRED – Java
    graph logic!
  id: totrans-12
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 性能——避免使用part_of关系，需要管理扩展——必须使用Java图逻辑！
- en: Versioning is hard
  id: totrans-13
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 版本控制是困难的
- en: ElasticSearch
  id: totrans-14
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 弹性搜索
- en: ~ by mdavey on December 2, 2015.
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: ~ mdavey于2015年12月2日。
- en: Posted in [Languages](https://mdavey.wordpress.com/category/languages/)
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: 发布于[语言](https://mdavey.wordpress.com/category/languages/)分类
