- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 06:27:21'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Productivity Myth | Tales from a Trading Desk
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://mdavey.wordpress.com/2013/04/19/productivity-myth/#0001-01-01](https://mdavey.wordpress.com/2013/04/19/productivity-myth/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Productivity Myth
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: “How the Productivity Myth is Killing Your Startup” is worth a [read](https://medium.com/about-work/1cd9fbf8ca15),
    particular the point in “The Dire Consequences of the Productivity Myth”
  prefs: []
  type: TYPE_NORMAL
- en: ~ by mdavey on April 19, 2013.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [Agile](https://mdavey.wordpress.com/category/agile/)
  prefs: []
  type: TYPE_NORMAL
