- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-18 06:27:21'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 06:27:21
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Productivity Myth | Tales from a Trading Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 生产力神话 | 交易桌上的故事
- en: 来源：[https://mdavey.wordpress.com/2013/04/19/productivity-myth/#0001-01-01](https://mdavey.wordpress.com/2013/04/19/productivity-myth/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://mdavey.wordpress.com/2013/04/19/productivity-myth/#0001-01-01](https://mdavey.wordpress.com/2013/04/19/productivity-myth/#0001-01-01)
- en: Productivity Myth
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 生产力神话
- en: “How the Productivity Myth is Killing Your Startup” is worth a [read](https://medium.com/about-work/1cd9fbf8ca15),
    particular the point in “The Dire Consequences of the Productivity Myth”
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: “生产力神话如何杀死你的初创公司”值得一读（特别是“生产力神话的严重后果”这一部分）
- en: ~ by mdavey on April 19, 2013.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: ~ mdavey于2013年4月19日。
- en: Posted in [Agile](https://mdavey.wordpress.com/category/agile/)
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 发布于[敏捷](https://mdavey.wordpress.com/category/agile/)
