- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-18 13:40:50'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-18 13:40:50'
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Quantifiable Edges: How To Trade The Choppiest Environment In 50 Years'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 可量化边缘：如何交易过去50年中最波动的环境
- en: 来源：[http://quantifiableedges.blogspot.com/2008/08/how-to-trade-choppiest-environment-in.html#0001-01-01](http://quantifiableedges.blogspot.com/2008/08/how-to-trade-choppiest-environment-in.html#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[http://quantifiableedges.blogspot.com/2008/08/how-to-trade-choppiest-environment-in.html#0001-01-01](http://quantifiableedges.blogspot.com/2008/08/how-to-trade-choppiest-environment-in.html#0001-01-01)
- en: If you trade trend or breakout strategies and have found the market difficult
    in the last year or so, I’m about to show a prime reason for that diffuclty. Below
    is a strategy that buys the S&P 500 on the close of any up day. The position is
    closed at the close of a down day. Essentially your looking to buy strength and
    sit out weakness.
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 如果您进行趋势或突破策略交易，并且在过去一年左右发现市场困难，我将展示一个主要原因。以下是一种策略，该策略在任何上涨日收盘时买入标准普尔500指数。该仓位在下跌日收盘时平仓。本质上，您正在寻找强势买入并避开弱势。
- en: '[![](img/626395a4bfb4a82eef8f9c8c0dd45417.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiXVr2e1jTd0R8CusOX3UNajAjbjQ6tCpC8yozP8heex3-JU8FwWbDxkzQY-8oVt6s1ojnBdOR-HswN1gmBVuJevLLeGEOpLzMrVOo2HV0k1MQ0lrrTMlUacuNO3FeQy-rG4zxmmDZbyf0/s1600-h/2008-8-21+SPX+buy+up+sell+down.bmp)'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '[![](img/626395a4bfb4a82eef8f9c8c0dd45417.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiXVr2e1jTd0R8CusOX3UNajAjbjQ6tCpC8yozP8heex3-JU8FwWbDxkzQY-8oVt6s1ojnBdOR-HswN1gmBVuJevLLeGEOpLzMrVOo2HV0k1MQ0lrrTMlUacuNO3FeQy-rG4zxmmDZbyf0/s1600-h/2008-8-21+SPX+buy+up+sell+down.bmp)'
- en: This strategy worked well in the 90’s, but since the market topped in 2000,
    it has performed poorly. Since the Spring of 2007 it has really accelerated lower.
    What this means is that performance following up days has been especially bad.
    It suggests the environenment has been especially choppy. Whereas strength begat
    strength in the 90’s, it has led to immediate weakness since.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 这种策略在90年代表现不错，但自2000年市场顶部以来表现不佳。自2007年春季以来，其下跌速度加快。这意味着在上涨日后的表现特别糟糕。这表明市场环境特别波动。在90年代，强势带来了更强势，但自那时以来，强势导致了立即的弱势。
- en: Now let’s take a look at downside follow through. In this case the strategy
    is to sell short on any down day and then cover on an up day.
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 现在让我们来看看下跌的跟随。在这种情况下，策略是在任何下跌日做空，然后在上涨日平仓。
- en: '[![](img/aa9b9db23a4c7d7573973fca5dec08f2.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj0x61rc9dEZE_90sHYBe0qvZRj3lcnYZ38oovFPiv5RK3v1AD8C6S9pHflPH2HLfVrahU8de-7xya0RAW_DN2J72-siQaiQ5IEZe8NOAUNS9MaXLaLbwzVbZNfxPuFv6FQYkk6D85LcrU/s1600-h/2008-8-21+SPX+short+down+cover+up.bmp)'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: '[![](img/aa9b9db23a4c7d7573973fca5dec08f2.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj0x61rc9dEZE_90sHYBe0qvZRj3lcnYZ38oovFPiv5RK3v1AD8C6S9pHflPH2HLfVrahU8de-7xya0RAW_DN2J72-siQaiQ5IEZe8NOAUNS9MaXLaLbwzVbZNfxPuFv6FQYkk6D85LcrU/s1600-h/2008-8-21+SPX+short+down+cover+up.bmp)'
- en: This was a break-even strategy through July of 2002\. Since then it has done
    terrible. Interestingly, it’s done especially bad over the last year plus. Even
    though the market has fallen precipitously, the manner in which it has occurred
    has made it difficult to profit if you’re trying to short breakdowns. Down days
    have been followed by up days.
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 这是一个在2002年7月前的盈亏平衡策略。从那时起，它表现糟糕。有趣的是，在过去一年多的时间里，它表现尤其糟糕。尽管市场急剧下跌，但由于其发生的方式，如果您试图做空突破，那么很难获利。下跌日后都是上涨日。
- en: 'What about a combination strategy? Buy strength and short weakness in anticipation
    of further follow through. Below is a chart with the combo strategy:'
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 如何组合策略？买入强势并在预期进一步跟随的时候卖空弱势。以下是使用组合策略的图表：
- en: '[![](img/02f1a025fa07278f525458940bef7444.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg5oG4Sz4q-LJmfiRWqgpRRHx7qFg7XA7hpg0vwavXirJLWW8tn8uA3v2gXBQlBznTVp7c17oma9WF7tJWff1SeioGQG3_HExP5NCpPJtbzrd3bgTdyTbb9qTon7eCNXSisnCoUklh-vZg/s1600-h/2008-8-21+buy+and+short+15+years.bmp)'
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: '[![](img/02f1a025fa07278f525458940bef7444.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg5oG4Sz4q-LJmfiRWqgpRRHx7qFg7XA7hpg0vwavXirJLWW8tn8uA3v2gXBQlBznTVp7c17oma9WF7tJWff1SeioGQG3_HExP5NCpPJtbzrd3bgTdyTbb9qTon7eCNXSisnCoUklh-vZg/s1600-h/2008-8-21+buy+and+short+15+years.bmp)'
- en: Again, since March 2007 this strategy would have experienced an incredible freefall.
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 自2007年3月以来，这种策略经历了令人难以置信的自由落体。
- en: Perhaps it would be best to take a step back, though. In the next chart I show
    back to 1960 instead of 1993 in an effort to find other periods where choppiness
    has been so prevalent.
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: 或许最好退一步看看。在下一个图表中，我展示了从1960年而不是1993年开始，以寻找其他波动如此严重的时期。
- en: '[![](img/f681ff0881478ee1babeb7bafcb95cca.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh7BzDYtQz9dVTOz8LYgfQ5tfKHlGBwyZcLlkrF-vAKWTSu_uB2gMCRyP0ez3h6-As9sxeCPVaLmOvadyIOYThW2Xm0PLA2LhokJMUQkd_5gobqE1TKMt99JWC9KGJpWgCoT23jivY4nVk/s1600-h/2008-8-21+buy+and+short+50+years.bmp)'
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: '![图片](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh7BzDYtQz9dVTOz8LYgfQ5tfKHlGBwyZcLlkrF-vAKWTSu_uB2gMCRyP0ez3h6-As9sxeCPVaLmOvadyIOYThW2Xm0PLA2LhokJMUQkd_5gobqE1TKMt99JWC9KGJpWgCoT23jivY4nVk/s1600-h/2008-8-21+buy+and+short+50+years.bmp)'
- en: As you can see, buying after strong days and selling after weak ones worked
    well for 40 years. In 2000 that changed, and the last year and a half is the worst
    it has ever been with regards to follow through. This would suggest that strategies
    that may have worked well for forty years or more could be suffering greatly now.
    Traders should consider the current choppy market behavior when designing strategies.
    Buying weakness and selling strength is working better than buying strength and
    selling weakness. They could also monitor charts like these to see if tendencies
    begin to revert back to pre-2000\. If tendencies do revert, adjustments may be
    needed.
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: 正如你所见，在强劲的日子里买入，在疲软的日子里卖出，这种策略在过去40年中非常有效。2000年之后，这种情况发生了变化，过去一年半是自2000年以来跟随趋势表现最差的时候。这表明那些可能在过去40年或更长时间内运作良好的策略现在可能遭受巨大损失。交易员在设计策略时应考虑当前的市场波动行为。在弱势中买入，在强势中卖出，其效果比在强势中买入，在弱势中卖出要好。他们还可以监控这些图表，看看趋势是否开始回归2000年之前。如果趋势确实回归，可能需要进行调整。
- en: '-----------------------------------------------------------------'
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: '-----------------------------------------------------------------'
- en: 'Update: I just saw that Dr. Brett Steenbarger also addressed this topic in
    his blog today. He looked at it from an international standpoint as well.'
  id: totrans-19
  prefs: []
  type: TYPE_NORMAL
  zh: 更新：我刚刚看到Dr. Brett Steenbarger在他的博客上也谈到了这个话题。他从国际角度进行了分析。
- en: '[Click here](http://traderfeed.blogspot.com/2008/08/short-term-reversal-patterns-among.html)'
  id: totrans-20
  prefs: []
  type: TYPE_NORMAL
  zh: 请点击[这里](http://traderfeed.blogspot.com/2008/08/short-term-reversal-patterns-among.html)
- en: to see his findings.
  id: totrans-21
  prefs: []
  type: TYPE_NORMAL
  zh: 以查看他的发现。
- en: '---------------------------------------------------------------------'
  id: totrans-22
  prefs: []
  type: TYPE_NORMAL
  zh: '---------------------------------------------------------------------'
