- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-12 19:06:17'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Quantitative Trading: The best environment for quantitative trading'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[http://epchan.blogspot.com/2009/10/best-environment-for-quantitative.html#0001-01-01](http://epchan.blogspot.com/2009/10/best-environment-for-quantitative.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'Let me talk about a topic that is far more mundane than the usual high-brow
    theoretical discussions of strategies and algorithms, but that has no less long-term
    impact on the bottom line: what is the best office environment for research and
    execution of quantitative trading strategies?'
  prefs: []
  type: TYPE_NORMAL
- en: I have worked in different office environments before, so I feel qualified to
    offer an informed opinion.
  prefs: []
  type: TYPE_NORMAL
- en: 'At Morgan Stanley, I huddled over a desk that is semi-partitioned from the
    rest of the office: nobody could see or bother me unless I or they stood up. At
    Credit Suisse, I shared an office with 2 other prop trading colleagues, one of
    whom was prone to freely sharing his opinion on various current affairs with his
    officemates. (On the other hand, he complained my biting an apple for lunch was
    too loud for him.) At Maple, a hedge fund in New Jersey, I shared an office with
    about 100 other colleagues on the trading floor, many of whom were prone to same
    opinion-sharing temptation.'
  prefs: []
  type: TYPE_NORMAL
- en: Here at my own firm, I sit in solitude (except for my cat) in my basement office,
    my beloved
  prefs: []
  type: TYPE_NORMAL
- en: '[classical FM](http://www.classicfm.co.uk/on-air/ways-of-listening/)'
  prefs: []
  type: TYPE_NORMAL
- en: streaming over the internet, my desktop electronically connected to my partner
    in our Chicago office, our trading servers at Amazon and elsewhere, and other
    clients and partners around the world, but unmolested throughout the day unless
    I voluntarily pick up the phone or answer an email or instant message.
  prefs: []
  type: TYPE_NORMAL
- en: Can you guess which environment is the one I find the most productive? Which
    one has the least stress? And which one contributes most to the bottom line of
    my employers/partners/clients?
  prefs: []
  type: TYPE_NORMAL
- en: '(Hint 1: read Timothy Ferriss'' book'
  prefs: []
  type: TYPE_NORMAL
- en: '[The 4-Hour Workweek](http://www.amazon.com/gp/product/0307353133?ie=UTF8&tag=quantitativet-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=0307353133)'
  prefs: []
  type: TYPE_NORMAL
- en: . This guy checks his email only once a week.)
  prefs: []
  type: TYPE_NORMAL
- en: '(Hint 2: my trading Sharpe ratio went from negative to >7.)'
  prefs: []
  type: TYPE_NORMAL
- en: P.S. I look forward to meeting some of you at the
  prefs: []
  type: TYPE_NORMAL
- en: '[Automated Trading Conference](http://www.technicalanalyst.co.uk/conferences/autoconf09.htm)'
  prefs: []
  type: TYPE_NORMAL
- en: in London this Friday (my talk will start at 0900), and others at my
  prefs: []
  type: TYPE_NORMAL
- en: '[pairs trading workshop](http://www.technicalanalyst.co.uk/training/backtestingEC.htm)'
  prefs: []
  type: TYPE_NORMAL
- en: on the preceding two days.
  prefs: []
  type: TYPE_NORMAL
