- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 13:33:48'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Quantifiable Edges: The Most Volatile Market Environment...Ever?'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[http://quantifiableedges.blogspot.com/2008/11/most-volatile-market-environmentever.html#0001-01-01](http://quantifiableedges.blogspot.com/2008/11/most-volatile-market-environmentever.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: '[In my last post](http://quantifiableedges.blogspot.com/2008/11/long-term-view-of-average-gap-sizes.html)'
  prefs: []
  type: TYPE_NORMAL
- en: I looked at the increased volatility based on the size of the average overnight
    gap in SPY. Today I’ll examine the current market’s volatility based on its Average
    True Range Percent.
  prefs: []
  type: TYPE_NORMAL
- en: In the chart below I show the Dow Jones Industrial Average from 1986 – present.
    The yellow line represents the 30-day average true range on a percentage basis.
    The average true range over the last 30 days closed at an astonishing 6.02% on
    Wednesday.
  prefs: []
  type: TYPE_NORMAL
- en: '[![](img/24680a352633f5ca86713aa9b0523b75.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjhFB7LuvJksv1gvgKYnUZZnmA9lSkNWb_fu-lAp8B36AMTGygM8C7VqcvhfYKYgxjZ0YNUp3mSxmZnDLCXXLiToUYwtit2Q0aS_7RhLfOxo0LoiEUkC1ofxuOTIpxuMHdKkPxV7Fm2wFg/s1600-h/2008-11-12+DJI+ATRpct+1986-present.png)'
  prefs: []
  type: TYPE_NORMAL
- en: It appears the only time since 1986 where it has come close the current 6% level
    was during the Crash of ’87 period when it poked just above 6\. In actuality,
    though, the comparison isn’t quite fair due to the way the range was calculated
    previous to 1992\.
  prefs: []
  type: TYPE_NORMAL
- en: '[From Investopedia](http://www.investopedia.com/terms/t/theoreticaldowjonesindex.asp)'
  prefs: []
  type: TYPE_NORMAL
- en: ':'
  prefs: []
  type: TYPE_NORMAL
- en: '***Theoretical Dow Jones Index** A method of calculating a Dow Jones index
    (most often the DJIA) that assumes all index components hit their high or low
    at the same time during the day.'
  prefs: []
  type: TYPE_NORMAL
- en: In other words, the "theoretical Dow" uses the daily highs for all 30 Dow components
    to calculate the index high, and the lows to calculate the index low. In January
    of 1992,* *Dow Jones* *started using the "actual" method, which calculates the
    index at 10-second intervals throughout the day. Before this point, the theoretical
    calculation was the only way to compute the high and low of the index. This method
    assumes that all* *stocks* *hit their high or low at the same time. Because this
    rarely happens, the theoretical high will almost always be higher than the actual,
    and the theoretical low will almost always be lower than the actual.*
  prefs: []
  type: TYPE_NORMAL
- en: Taking the pre – ’92 exaggerated range into account, it appears almost certain
    that the recent market has displayed a higher Average True Range % than 1987\.
    Going back further in history, the only other period where ranges approached these
    levels were…the 1930’s.
  prefs: []
  type: TYPE_NORMAL
- en: '[![](img/e3e84285eb738eab9146d7b91455cd8c.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgvecAX-yvfN5grkvx4FBAafrY_vE8WuQUIr8X8CzZ_mOVUAlKwYYemh9jWenebMYlPRkusGC-4nZ-QexS2zZZeP4NgJMwDF9CPmUQ6v0iCKJKY_pDTp-y8u6ZJo7eQOA31Fq8qGGRUo-A/s1600-h/2008-11-12+DJI+ATRpct+1929-1940.png)'
  prefs: []
  type: TYPE_NORMAL
- en: Even during this period the only time where the average true range percent got
    much above 6% was following the Crash of ’29 when it hit nearly 7%. Since the
    ranges were exaggerated due to use of the Theoretical Dow calculation, it’s possible
    that the current environment may actually be the most volatile.
  prefs: []
  type: TYPE_NORMAL
- en: You may notice from the charts that the spikes in volatility tend to occur near
    market bottoms. An ATR spike can alert you that a bottom may be coming. Like many
    indicators that use moving averages, though, the 30-day ATR% is a lagging indicator.
    It typically peaks after the bottom has been made. Look for this measure to turn
    down again once a bottom (at least a temporary bottom) is in place.
  prefs: []
  type: TYPE_NORMAL
