- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 13:40:50'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Quantifiable Edges: How To Trade The Choppiest Environment In 50 Years'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[http://quantifiableedges.blogspot.com/2008/08/how-to-trade-choppiest-environment-in.html#0001-01-01](http://quantifiableedges.blogspot.com/2008/08/how-to-trade-choppiest-environment-in.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: If you trade trend or breakout strategies and have found the market difficult
    in the last year or so, I’m about to show a prime reason for that diffuclty. Below
    is a strategy that buys the S&P 500 on the close of any up day. The position is
    closed at the close of a down day. Essentially your looking to buy strength and
    sit out weakness.
  prefs: []
  type: TYPE_NORMAL
- en: '[![](img/626395a4bfb4a82eef8f9c8c0dd45417.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiXVr2e1jTd0R8CusOX3UNajAjbjQ6tCpC8yozP8heex3-JU8FwWbDxkzQY-8oVt6s1ojnBdOR-HswN1gmBVuJevLLeGEOpLzMrVOo2HV0k1MQ0lrrTMlUacuNO3FeQy-rG4zxmmDZbyf0/s1600-h/2008-8-21+SPX+buy+up+sell+down.bmp)'
  prefs: []
  type: TYPE_NORMAL
- en: This strategy worked well in the 90’s, but since the market topped in 2000,
    it has performed poorly. Since the Spring of 2007 it has really accelerated lower.
    What this means is that performance following up days has been especially bad.
    It suggests the environenment has been especially choppy. Whereas strength begat
    strength in the 90’s, it has led to immediate weakness since.
  prefs: []
  type: TYPE_NORMAL
- en: Now let’s take a look at downside follow through. In this case the strategy
    is to sell short on any down day and then cover on an up day.
  prefs: []
  type: TYPE_NORMAL
- en: '[![](img/aa9b9db23a4c7d7573973fca5dec08f2.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj0x61rc9dEZE_90sHYBe0qvZRj3lcnYZ38oovFPiv5RK3v1AD8C6S9pHflPH2HLfVrahU8de-7xya0RAW_DN2J72-siQaiQ5IEZe8NOAUNS9MaXLaLbwzVbZNfxPuFv6FQYkk6D85LcrU/s1600-h/2008-8-21+SPX+short+down+cover+up.bmp)'
  prefs: []
  type: TYPE_NORMAL
- en: This was a break-even strategy through July of 2002\. Since then it has done
    terrible. Interestingly, it’s done especially bad over the last year plus. Even
    though the market has fallen precipitously, the manner in which it has occurred
    has made it difficult to profit if you’re trying to short breakdowns. Down days
    have been followed by up days.
  prefs: []
  type: TYPE_NORMAL
- en: 'What about a combination strategy? Buy strength and short weakness in anticipation
    of further follow through. Below is a chart with the combo strategy:'
  prefs: []
  type: TYPE_NORMAL
- en: '[![](img/02f1a025fa07278f525458940bef7444.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg5oG4Sz4q-LJmfiRWqgpRRHx7qFg7XA7hpg0vwavXirJLWW8tn8uA3v2gXBQlBznTVp7c17oma9WF7tJWff1SeioGQG3_HExP5NCpPJtbzrd3bgTdyTbb9qTon7eCNXSisnCoUklh-vZg/s1600-h/2008-8-21+buy+and+short+15+years.bmp)'
  prefs: []
  type: TYPE_NORMAL
- en: Again, since March 2007 this strategy would have experienced an incredible freefall.
  prefs: []
  type: TYPE_NORMAL
- en: Perhaps it would be best to take a step back, though. In the next chart I show
    back to 1960 instead of 1993 in an effort to find other periods where choppiness
    has been so prevalent.
  prefs: []
  type: TYPE_NORMAL
- en: '[![](img/f681ff0881478ee1babeb7bafcb95cca.png)](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh7BzDYtQz9dVTOz8LYgfQ5tfKHlGBwyZcLlkrF-vAKWTSu_uB2gMCRyP0ez3h6-As9sxeCPVaLmOvadyIOYThW2Xm0PLA2LhokJMUQkd_5gobqE1TKMt99JWC9KGJpWgCoT23jivY4nVk/s1600-h/2008-8-21+buy+and+short+50+years.bmp)'
  prefs: []
  type: TYPE_NORMAL
- en: As you can see, buying after strong days and selling after weak ones worked
    well for 40 years. In 2000 that changed, and the last year and a half is the worst
    it has ever been with regards to follow through. This would suggest that strategies
    that may have worked well for forty years or more could be suffering greatly now.
    Traders should consider the current choppy market behavior when designing strategies.
    Buying weakness and selling strength is working better than buying strength and
    selling weakness. They could also monitor charts like these to see if tendencies
    begin to revert back to pre-2000\. If tendencies do revert, adjustments may be
    needed.
  prefs: []
  type: TYPE_NORMAL
- en: '-----------------------------------------------------------------'
  prefs: []
  type: TYPE_NORMAL
- en: 'Update: I just saw that Dr. Brett Steenbarger also addressed this topic in
    his blog today. He looked at it from an international standpoint as well.'
  prefs: []
  type: TYPE_NORMAL
- en: '[Click here](http://traderfeed.blogspot.com/2008/08/short-term-reversal-patterns-among.html)'
  prefs: []
  type: TYPE_NORMAL
- en: to see his findings.
  prefs: []
  type: TYPE_NORMAL
- en: '---------------------------------------------------------------------'
  prefs: []
  type: TYPE_NORMAL
