- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-18 14:33:06'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 14:33:06
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Retirement : simulating wealth with random returns, inflation and withdrawals
    – Shiny web application | Systematic Investor'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 退休：模拟随机回报、通货膨胀和提款的财富 – Shiny网页应用 | 系统投资者
- en: 来源：[https://systematicinvestor.wordpress.com/2013/04/06/retirement-simulating-wealth-with-random-returns-inflation-and-withdrawals-shiny-web-application/#0001-01-01](https://systematicinvestor.wordpress.com/2013/04/06/retirement-simulating-wealth-with-random-returns-inflation-and-withdrawals-shiny-web-application/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://systematicinvestor.wordpress.com/2013/04/06/retirement-simulating-wealth-with-random-returns-inflation-and-withdrawals-shiny-web-application/#0001-01-01](https://systematicinvestor.wordpress.com/2013/04/06/retirement-simulating-wealth-with-random-returns-inflation-and-withdrawals-shiny-web-application/#0001-01-01)
- en: 'Today, I want to share the [Retirement : simulating wealth with random returns,
    inflation and withdrawals](http://glimmer.rstudio.com/systematicin/retirement.withdrawal/)
    – [Shiny](http://www.rstudio.com/shiny/) web application (code at [GitHub](https://github.com/systematicinvestor/SIT/tree/master/Shiny/retirement.withdrawal)).'
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 今天，我想分享这个[退休：模拟随机回报、通货膨胀和提款的财富](http://glimmer.rstudio.com/systematicin/retirement.withdrawal/)
    – [Shiny](http://www.rstudio.com/shiny/)网页应用（代码在[GitHub](https://github.com/systematicinvestor/SIT/tree/master/Shiny/retirement.withdrawal/)）。
- en: This application was developed and contributed by Pierre Chretien, I only made
    minor updates. This is application is a great example of how easy it is to convert
    your R script into interactive [Shiny](http://www.rstudio.com/shiny/) web application.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 这个应用是由Pierre Chretien开发和贡献的，我只是做了一些小更新。这个应用很好地展示了将你的R脚本转换成互动性[Shiny](http://www.rstudio.com/shiny/)网页应用是多么简单。
- en: 'Please see below the sample script to simulate wealth random returns, inflation
    and withdrawals:'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 请参阅下面的示例脚本，以模拟财富的随机回报、通货膨胀和提款：
- en: '[PRE0]'
  id: totrans-9
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: '[![plot1](img/79a1b9e3afce16531217c86259677d86.png)](https://systematicinvestor.wordpress.com/wp-content/uploads/2013/04/plot1.png)'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: '![plot1](img/79a1b9e3afce16531217c86259677d86.png)'
- en: 'The corresponding [Shiny](http://www.rstudio.com/shiny/) web application consists
    of two files:'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 相应的[Shiny](http://www.rstudio.com/shiny/)网页应用包含两个文件：
- en: ui.r – User Interface
  id: totrans-12
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: ui.r – 用户界面
- en: server.r – R simulations and calculations
  id: totrans-13
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: server.r – R模拟和计算
- en: 'Following is the user interface (ui.r) that maps and describes required inputs
    for the retirement simulation:'
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 以下是用于描述退休模拟所需输入的用户界面（ui.r）：
- en: '[PRE1]'
  id: totrans-15
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: 'The last step is modify the retirement simulation logic to use user inputs:'
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: 最后一步是修改退休模拟逻辑以使用用户输入：
- en: '[PRE2]'
  id: totrans-17
  prefs: []
  type: TYPE_PRE
  zh: '[PRE2]'
- en: We all done now!!! [Shiny](http://www.rstudio.com/shiny/) is amazing in the
    way it allows you to convert your script into interactive web application with
    just two simple steps.
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: 我们都做完了！！！Shiny在允许你仅用两个简单步骤将你的脚本转换为互动性网页应用方面真是太棒了。
- en: 'Please play around with the [Retirement : simulating wealth with random returns,
    inflation and withdrawals](http://glimmer.rstudio.com/systematicin/retirement.withdrawal/)
    – [Shiny](http://www.rstudio.com/shiny/) web application (code at [GitHub](https://github.com/systematicinvestor/SIT/tree/master/Shiny/retirement.withdrawal)).'
  id: totrans-19
  prefs: []
  type: TYPE_NORMAL
  zh: 请尝试使用[退休：模拟随机回报、通货膨胀和提款的财富](http://glimmer.rstudio.com/systematicin/retirement.withdrawal/)
    – [Shiny](http://www.rstudio.com/shiny/)网页应用（代码在[GitHub](https://github.com/systematicinvestor/SIT/tree/master/Shiny/retirement.withdrawal/)）。
- en: Have a good weekend
  id: totrans-20
  prefs: []
  type: TYPE_NORMAL
  zh: 周末愉快
