- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 14:33:06'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Retirement : simulating wealth with random returns, inflation and withdrawals
    – Shiny web application | Systematic Investor'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://systematicinvestor.wordpress.com/2013/04/06/retirement-simulating-wealth-with-random-returns-inflation-and-withdrawals-shiny-web-application/#0001-01-01](https://systematicinvestor.wordpress.com/2013/04/06/retirement-simulating-wealth-with-random-returns-inflation-and-withdrawals-shiny-web-application/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'Today, I want to share the [Retirement : simulating wealth with random returns,
    inflation and withdrawals](http://glimmer.rstudio.com/systematicin/retirement.withdrawal/)
    – [Shiny](http://www.rstudio.com/shiny/) web application (code at [GitHub](https://github.com/systematicinvestor/SIT/tree/master/Shiny/retirement.withdrawal)).'
  prefs: []
  type: TYPE_NORMAL
- en: This application was developed and contributed by Pierre Chretien, I only made
    minor updates. This is application is a great example of how easy it is to convert
    your R script into interactive [Shiny](http://www.rstudio.com/shiny/) web application.
  prefs: []
  type: TYPE_NORMAL
- en: 'Please see below the sample script to simulate wealth random returns, inflation
    and withdrawals:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
- en: '[![plot1](img/79a1b9e3afce16531217c86259677d86.png)](https://systematicinvestor.wordpress.com/wp-content/uploads/2013/04/plot1.png)'
  prefs: []
  type: TYPE_NORMAL
- en: 'The corresponding [Shiny](http://www.rstudio.com/shiny/) web application consists
    of two files:'
  prefs: []
  type: TYPE_NORMAL
- en: ui.r – User Interface
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: server.r – R simulations and calculations
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Following is the user interface (ui.r) that maps and describes required inputs
    for the retirement simulation:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE1]'
  prefs: []
  type: TYPE_PRE
- en: 'The last step is modify the retirement simulation logic to use user inputs:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE2]'
  prefs: []
  type: TYPE_PRE
- en: We all done now!!! [Shiny](http://www.rstudio.com/shiny/) is amazing in the
    way it allows you to convert your script into interactive web application with
    just two simple steps.
  prefs: []
  type: TYPE_NORMAL
- en: 'Please play around with the [Retirement : simulating wealth with random returns,
    inflation and withdrawals](http://glimmer.rstudio.com/systematicin/retirement.withdrawal/)
    – [Shiny](http://www.rstudio.com/shiny/) web application (code at [GitHub](https://github.com/systematicinvestor/SIT/tree/master/Shiny/retirement.withdrawal)).'
  prefs: []
  type: TYPE_NORMAL
- en: Have a good weekend
  prefs: []
  type: TYPE_NORMAL
