- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-18 14:33:31'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 14:33:31
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Sector Rotation Back Test Shiny web application | Systematic Investor
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 板块轮动回测Shiny网络应用 | 系统投资者
- en: 来源：[https://systematicinvestor.wordpress.com/2013/02/18/sector-rotation-back-test-shiny-web-application/#0001-01-01](https://systematicinvestor.wordpress.com/2013/02/18/sector-rotation-back-test-shiny-web-application/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://systematicinvestor.wordpress.com/2013/02/18/sector-rotation-back-test-shiny-web-application/#0001-01-01](https://systematicinvestor.wordpress.com/2013/02/18/sector-rotation-back-test-shiny-web-application/#0001-01-01)
- en: '[Home](https://systematicinvestor.wordpress.com/ "Go to homepage")'
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: '[首页](https://systematicinvestor.wordpress.com/ "前往主页")'
- en: '>'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '>'
- en: '[R](https://systematicinvestor.wordpress.com/category/r/)'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: '[R](https://systematicinvestor.wordpress.com/category/r/)'
- en: ','
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: ','
- en: '[Shiny](https://systematicinvestor.wordpress.com/category/shiny/)'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: '[Shiny](https://systematicinvestor.wordpress.com/category/shiny/)'
- en: Sector Rotation Back Test Shiny web application
  id: totrans-11
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 板块轮动回测Shiny网络应用
- en: Sector Rotation Back Test Shiny web application
  id: totrans-12
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 板块轮动回测Shiny网络应用
- en: Today, I want to share the [Sector Rotation Back Test](http://glimmer.rstudio.com/systematicin/sector.rotation/)
    application (code at [GitHub](https://github.com/systematicinvestor/SIT/tree/master/Shiny/sector.rotation)).
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: 今天，我想分享[板块轮动回测](http://glimmer.rstudio.com/systematicin/sector.rotation/)应用（代码在[GitHub](https://github.com/systematicinvestor/SIT/tree/master/Shiny/sector.rotation/)）。
- en: This is the last application in the series of examples (I have shared 5 examples)
    that will demonstrate the amazing [Shiny](http://www.rstudio.com/shiny/) framework
    and [Systematic Investor Toolbox](https://systematicinvestor.wordpress.com/systematic-investor-toolbox/)
    to analyze stocks, make back-tests, and create summary reports.
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 这是系列示例中的最后一个应用（我已经分享了5个示例），将展示令人惊叹的[Shiny](http://www.rstudio.com/shiny/)框架和[系统投资者工具箱](https://systematicinvestor.wordpress.com/systematic-investor-toolbox/)，用于分析股票、进行回测和创建摘要报告。
- en: The motivation for this series of posts is to show how to translate, with minimal
    effort, your back-test scripts into live web applications that can either be run
    from the Shiny server or your personal computer.
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: 这一系列文章的动机是展示如何以最小的努力，将你的回测脚本翻译成可以从Shiny服务器或你的个人电脑运行的实时网络应用。
- en: Please note that Back Test applications take longer time to update the plots/tables
    and hence maybe more appropriate to run from your local computer.
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: 请注意，回测应用更新图表/表格需要更长的时间，因此可能更适合从你的本地电脑运行。
- en: 'For example to run [Sector Rotation](http://glimmer.rstudio.com/systematicin/one.stock/)
    application from your computer, you first need to install [Shiny](http://www.rstudio.com/shiny/).
    And next execute following commands:'
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: 例如，要从你的电脑运行[板块轮动](http://glimmer.rstudio.com/systematicin/one.stock/)应用，你首先需要安装[Shiny](http://www.rstudio.com/shiny/)。然后执行以下命令：
- en: '[PRE0]'
  id: totrans-18
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
