- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 14:33:31'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Sector Rotation Back Test Shiny web application | Systematic Investor
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://systematicinvestor.wordpress.com/2013/02/18/sector-rotation-back-test-shiny-web-application/#0001-01-01](https://systematicinvestor.wordpress.com/2013/02/18/sector-rotation-back-test-shiny-web-application/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: '[Home](https://systematicinvestor.wordpress.com/ "Go to homepage")'
  prefs: []
  type: TYPE_NORMAL
- en: '>'
  prefs: []
  type: TYPE_NORMAL
- en: '[R](https://systematicinvestor.wordpress.com/category/r/)'
  prefs: []
  type: TYPE_NORMAL
- en: ','
  prefs: []
  type: TYPE_NORMAL
- en: '[Shiny](https://systematicinvestor.wordpress.com/category/shiny/)'
  prefs: []
  type: TYPE_NORMAL
- en: Sector Rotation Back Test Shiny web application
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Sector Rotation Back Test Shiny web application
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Today, I want to share the [Sector Rotation Back Test](http://glimmer.rstudio.com/systematicin/sector.rotation/)
    application (code at [GitHub](https://github.com/systematicinvestor/SIT/tree/master/Shiny/sector.rotation)).
  prefs: []
  type: TYPE_NORMAL
- en: This is the last application in the series of examples (I have shared 5 examples)
    that will demonstrate the amazing [Shiny](http://www.rstudio.com/shiny/) framework
    and [Systematic Investor Toolbox](https://systematicinvestor.wordpress.com/systematic-investor-toolbox/)
    to analyze stocks, make back-tests, and create summary reports.
  prefs: []
  type: TYPE_NORMAL
- en: The motivation for this series of posts is to show how to translate, with minimal
    effort, your back-test scripts into live web applications that can either be run
    from the Shiny server or your personal computer.
  prefs: []
  type: TYPE_NORMAL
- en: Please note that Back Test applications take longer time to update the plots/tables
    and hence maybe more appropriate to run from your local computer.
  prefs: []
  type: TYPE_NORMAL
- en: 'For example to run [Sector Rotation](http://glimmer.rstudio.com/systematicin/one.stock/)
    application from your computer, you first need to install [Shiny](http://www.rstudio.com/shiny/).
    And next execute following commands:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
