- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 06:07:44'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Silverlight: Build Business Applications? | Tales from a Trading Desk'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://mdavey.wordpress.com/2008/06/05/silverlight-build-business-applications/#0001-01-01](https://mdavey.wordpress.com/2008/06/05/silverlight-build-business-applications/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'Silverlight: Build Business Applications?'
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Looks to me like we could be in for an interesting [announcement](http://blogs.msdn.com/mswanson/archive/2008/05/28/pdc2008-registration-opens-with-preliminary-sessions.aspx)
    at PDC 2008 – “a new technology that makes it easy to build business applications
    in Silverlight” 😉
  prefs: []
  type: TYPE_NORMAL
- en: '**[Silverlight: Building Business Applications](http://www.microsoftpdc.com/Agenda/Sessions.aspx)**'
  prefs: []
  type: TYPE_NORMAL
- en: What if you could develop your solutions with the ease pioneered by Access,
    deploy them like an Internet application, and take advantage of the power of .NET?
    Learn about an exciting new technology that is all about making business applications
    for RIA (Rich Internet Applications) much easier to build. In this session, you’ll
    hear how we’ve made n-tier application development as simple as traditional 2-tier,
    provided application level solutions to developers, and how we’re doing all of
    this with the same.NET platform and tools on both the client and on the server.
  prefs: []
  type: TYPE_NORMAL
- en: Could this be [Volta](http://labs.live.com/volta/) for [Silverlight](http://labs.live.com/volta/blog/Volta+Secrets+Part+5++Silverlight.aspx)?
  prefs: []
  type: TYPE_NORMAL
- en: 'Sidebar: [Visual State Manager](http://electricbeach.org/?p=98)'
  prefs: []
  type: TYPE_NORMAL
- en: ~ by mdavey on June 5, 2008.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [Uncategorized](https://mdavey.wordpress.com/category/uncategorized/)
  prefs: []
  type: TYPE_NORMAL
- en: 'Tags: [Microsoft](https://mdavey.wordpress.com/tag/microsoft/)'
  prefs: []
  type: TYPE_NORMAL
