- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-18 06:07:44'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 06:07:44
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Silverlight: Build Business Applications? | Tales from a Trading Desk'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: Silverlight：构建商业应用程序？ | 交易桌上的故事
- en: 来源：[https://mdavey.wordpress.com/2008/06/05/silverlight-build-business-applications/#0001-01-01](https://mdavey.wordpress.com/2008/06/05/silverlight-build-business-applications/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://mdavey.wordpress.com/2008/06/05/silverlight-build-business-applications/#0001-01-01](https://mdavey.wordpress.com/2008/06/05/silverlight-build-business-applications/#0001-01-01)
- en: 'Silverlight: Build Business Applications?'
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: Silverlight：构建商业应用程序？
- en: Looks to me like we could be in for an interesting [announcement](http://blogs.msdn.com/mswanson/archive/2008/05/28/pdc2008-registration-opens-with-preliminary-sessions.aspx)
    at PDC 2008 – “a new technology that makes it easy to build business applications
    in Silverlight” 😉
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 看来我们可能会在2008年PDC上迎来一个有趣的[公告](http://blogs.msdn.com/mswanson/archive/2008/05/28/pdc2008-registration-opens-with-preliminary-sessions.aspx)——“一种使在Silverlight中构建商业应用程序变得简单的新技术”😉
- en: '**[Silverlight: Building Business Applications](http://www.microsoftpdc.com/Agenda/Sessions.aspx)**'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: '[Silverlight: Building Business Applications](http://www.microsoftpdc.com/Agenda/Sessions.aspx)'
- en: What if you could develop your solutions with the ease pioneered by Access,
    deploy them like an Internet application, and take advantage of the power of .NET?
    Learn about an exciting new technology that is all about making business applications
    for RIA (Rich Internet Applications) much easier to build. In this session, you’ll
    hear how we’ve made n-tier application development as simple as traditional 2-tier,
    provided application level solutions to developers, and how we’re doing all of
    this with the same.NET platform and tools on both the client and on the server.
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 如果你能像使用Access那样轻松地开发你的解决方案，将它们部署为互联网应用程序，并利用.NET的强大功能，那会怎样？了解一种令人兴奋的新技术，它全部关于使商业应用程序（RIA，富互联网应用程序）的构建变得更容易。在本会议中，您将了解到我们如何使n层应用程序开发像传统的2层一样简单，为开发者提供应用程序级解决方案，以及我们是如何使用相同的.NET平台和工具在客户端和服务器上实现这一切的。
- en: Could this be [Volta](http://labs.live.com/volta/) for [Silverlight](http://labs.live.com/volta/blog/Volta+Secrets+Part+5++Silverlight.aspx)?
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 这可能是为[Silverlight](http://labs.live.com/volta/blog/Volta+Secrets+Part+5++Silverlight.aspx)设计的[Volta](http://labs.live.com/volta/)吗？
- en: 'Sidebar: [Visual State Manager](http://electricbeach.org/?p=98)'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 侧边栏： [视觉状态管理器](http://electricbeach.org/?p=98)
- en: ~ by mdavey on June 5, 2008.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: ~ mdavey于2008年6月5日。
- en: Posted in [Uncategorized](https://mdavey.wordpress.com/category/uncategorized/)
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: 发布于 [未分类](https://mdavey.wordpress.com/category/uncategorized/)
- en: 'Tags: [Microsoft](https://mdavey.wordpress.com/tag/microsoft/)'
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 标签： [微软](https://mdavey.wordpress.com/tag/microsoft/)
