- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 05:41:58'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Test in Production Environment | Tales from a Trading Desk
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://mdavey.wordpress.com/2015/06/09/test-in-production-environment/#0001-01-01](https://mdavey.wordpress.com/2015/06/09/test-in-production-environment/#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Test in Production Environment
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: 'Nice short [article](http://www.infoq.com/articles/mobile-app-performance-testing)
    on application performance testing.  Its a shame that many companies still want
    to find excuses for not offering development access to production like environments:'
  prefs: []
  type: TYPE_NORMAL
- en: Variables such as firewalls, specific load balancing configurations, server’s
    memory configuration, etc., may severely influence on performance. It is best
    to test in production or simulated production. This will tend to be done in a
    non-destructive manner. But the principle is consistent, test everything both
    physical, hardware and network to a full picture of what happens when the app
    is launched and used.
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: I’m sure there is a formula one could come up with that offers visibility to
    the stakeholders on how much money they will incur from a cost of not testing
    in a production environment prior to production deployment.
  prefs: []
  type: TYPE_NORMAL
- en: ~ by mdavey on June 9, 2015.
  prefs: []
  type: TYPE_NORMAL
- en: Posted in [Agile](https://mdavey.wordpress.com/category/agile/)
  prefs: []
  type: TYPE_NORMAL
