- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 14:57:46'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Timely Portfolio: Applications of Interactivity to Finance'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[http://timelyportfolio.blogspot.com/2013/08/applications-of-interactivity-to-finance.html#0001-01-01](http://timelyportfolio.blogspot.com/2013/08/applications-of-interactivity-to-finance.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Of the nearly infinite ways of using [crossfilter](http://square.github.io/crossfilter/)
    and [dc.js](http://nickqizhu.github.io/dc.js/) in finance, the 2 that immediately
    came to my mind are signal analysis in system building and money manager analysis
    in due diligence.  My first very basic experiment explores a commonly known signal
    (RSI) on the daily S&P 500 since 1950.  Interactivity adds a lot to the experience. 
    I used R to grab and reshape the data and [slidify](http://slidify.org) to make
    it pretty.  Check it out by clicking [here](http://timelyportfolio.github.io/rCharts_crossfilter_dcjs/signal_slidify.html)
    or on the screenshot below.
  prefs: []
  type: TYPE_NORMAL
- en: '[![screenshot](img/14ebee485ddc4a6df264cb415b9f3293.png "screenshot")](http://timelyportfolio.github.io/rCharts_crossfilter_dcjs/signal_slidify.html)'
  prefs: []
  type: TYPE_NORMAL
- en: For another very fine example of dc.js and crossfilter in use with AAII Stockpicking
    strategy data, see this [fine site](http://www.acrodatics.com/).
  prefs: []
  type: TYPE_NORMAL
- en: '[![image](img/1d23e70f623e3b3faa0c2e0828d6fd82.png "image")](http://www.acrodatics.com/)'
  prefs: []
  type: TYPE_NORMAL
