- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-18 15:43:12'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 15:43:12
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Trading with Python: How to setup Python development environment'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: Python交易：如何设置Python开发环境
- en: 来源：[http://tradingwithpython.blogspot.com/2011/11/how-to-setup-python-development.html#0001-01-01](http://tradingwithpython.blogspot.com/2011/11/how-to-setup-python-development.html#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[http://tradingwithpython.blogspot.com/2011/11/how-to-setup-python-development.html#0001-01-01](http://tradingwithpython.blogspot.com/2011/11/how-to-setup-python-development.html#0001-01-01)
- en: If you would like to start playing with the code from this blog and write your
    own, you need to setup a development environment first. I've already put a summary
    of tools and software packages on the
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 如果你想要从这篇博客开始玩代码并编写自己的代码，你首先需要设置一个开发环境。我已经在这篇博客上总结了工具和软件包的概要。
- en: '[tools page](http://tradingwithpython.blogspot.com/p/setting-up-development-environment.html)'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '[工具页面](http://tradingwithpython.blogspot.com/p/setting-up-development-environment.html)'
- en: 'and to make it even easier, here are the steps you''ll need to follow to get
    up and running:'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 为了让它变得更容易，这里是你需要遵循的步骤，以开始运行：
- en: 1\. Install
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 1\. 安装
- en: '[PythonXY](http://code.google.com/p/pythonxy/wiki/Downloads)'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: '[PythonXY](http://code.google.com/p/pythonxy/wiki/Downloads)'
- en: '. : this includes Python 2.7 and tools Spyder, Ipython etc.'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: '. : 这包括Python 2.7和工具Spyder，Ipython等。'
- en: 2\. Install
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 2\. 安装
- en: '[Tortoise SVN](http://tortoisesvn.net/downloads.html)'
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: '[Tortoise SVN](http://tortoisesvn.net/downloads.html)'
- en: . This is a utility that you need to pull the source code from Google Code
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: . 这是一个工具，你可以使用它从Google Code拉取源代码
- en: 3\. Install
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: 3\. 安装
- en: '[Pandas](http://pypi.python.org/packages/2.7/p/pandas/pandas-0.5.0.win32-py2.7.exe#md5=c2badf1d82d48a57abcff72228d28cd9)'
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: '[Pandas](http://pypi.python.org/packages/2.7/p/pandas/pandas-0.5.0.win32-py2.7.exe#md5=c2badf1d82d48a57abcff72228d28cd9)'
- en: (time series library)
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: (时间序列库)
- en: This is all you need for now.
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: 现在所需要的全部东西就是这些。
- en: To get the code, use 'Svn Checkout' windows explorer context menu that is available
    after installing Tortoise SVN. Checkout like this (change Checkout directory to
    the location you want, but it should end with
  id: totrans-19
  prefs: []
  type: TYPE_NORMAL
  zh: 要获取代码，请使用在安装Tortoise SVN后可用的'Svn检出'窗口资源管理器上下文菜单。像这样进行检出（将检出目录更改为您想要的位置，但该位置应以
- en: '*tradingWithPython*'
  id: totrans-20
  prefs: []
  type: TYPE_NORMAL
  zh: '*tradingWithPython*'
- en: '):'
  id: totrans-21
  prefs: []
  type: TYPE_NORMAL
  zh: '):'
- en: If all goes well, the most recent version of the files will be downloaded. I'll
    be writing more code and improving current one, you'll be able to stay in sync
    with my code by using 'svn update' context menu.
  id: totrans-22
  prefs: []
  type: TYPE_NORMAL
  zh: 如果一切顺利，文件的最新版本将被下载。我会编写更多的代码并改进现有的代码，你可以通过使用'svn更新'上下文菜单来同步我的代码。
- en: The final step is to launch Spyder (through pythonXY launcher or start menu)
    and add the directory just above the '
  id: totrans-23
  prefs: []
  type: TYPE_NORMAL
  zh: 最终步骤是启动Spyder（通过pythonXY启动器或开始菜单），并将刚刚上方的目录添加到'
- en: '*tradingWithPython''*'
  id: totrans-24
  prefs: []
  type: TYPE_NORMAL
  zh: '*tradingWithPython''*'
- en: (in my example C:\Users\jev\Desktop') dir to python path . Do this with 'tools'->'PYTHONPATH
    manager'.
  id: totrans-25
  prefs: []
  type: TYPE_NORMAL
  zh: （在我的例子中是C:\Users\jev\Desktop') 目录添加到python路径。通过'工具'->'PYTHONPATH管理器'进行此操作。
- en: Ok, all done, now you can run the examples from \cookbok dir.
  id: totrans-26
  prefs: []
  type: TYPE_NORMAL
  zh: 好的，全部完成，现在你可以从\cookbok目录运行示例了。
