- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-18 05:32:37'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 05:32:37
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Training the algorithm | Tales from a Trading Desk
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 训练算法 | 交易桌上的故事
- en: 来源：[https://mdavey.wordpress.com/2016/05/09/training-the-algorithm/#0001-01-01](https://mdavey.wordpress.com/2016/05/09/training-the-algorithm/#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://mdavey.wordpress.com/2016/05/09/training-the-algorithm/#0001-01-01](https://mdavey.wordpress.com/2016/05/09/training-the-algorithm/#0001-01-01)
- en: Training the algorithm
  id: totrans-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 训练算法
- en: 'Interesting [article](http://www.bbc.co.uk/news/business-36129046) on the BBC
    recently, “Can a computer really recruit the best staff?”.  Some interesting take
    aways:'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 最近BBC上有篇有趣的[文章](http://www.bbc.co.uk/news/business-36129046)，标题是“计算机真的能招聘到最佳员工吗？”。
    有些有趣的观点：
- en: How we use our computers and phones logs our corporate activity, what we say
    on social networks does the same thing. When we use a keycard to get from department
    to department, that’s generating data about our movement across the workspace.
    Bill Nowaki calls all this data “artefacts”.
  id: totrans-8
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 我们如何使用电脑和手机记录了我们的工作活动，我们在社交网络上说的话也起到了同样的作用。当我们使用门禁卡在部门间移动时，这正在生成关于我们在工作空间中移动的数据。比尔·诺瓦基将所有这些数据称为“人工制品”。
- en: 'If the data is used in the right way, there are benefits:'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 如果数据以正确的方式使用，是有好处的：
- en: But it would also be a great aid to improving someone’s performance… if an organisation
    uses the data of its most successful people to give tips and hints to the laggards.
  id: totrans-10
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 但如果一个组织利用其最成功人士的数据来给表现不佳者提供提示和暗示，这对提高某人的表现将大有裨益。
- en: 'And why the algorithm might be better in some scenarios, or at least the algorithm
    will help highlight the issues:'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 为什么在某些情况下算法可能更胜一筹，或者至少算法将帮助突出这些问题：
- en: Study after study demonstrates a huge bias in the recruiting process… even in
    organisations which say they are committed to eliminating discrimination. White
    middle-aged men have a tendency to hire other white middle-aged men, whatever
    they intend. Robotised recruitment is blind to that sort of human influence.
  id: totrans-12
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 研究一次又一次地证明招聘过程中存在巨大的偏见……即使是在那些声称致力于消除歧视的组织中。 白人中年男性倾向于招聘其他白人中年男性，无论他们的意图如何。
    自动化招聘对这种人类影响视而不见。
- en: ~ by mdavey on May 9, 2016.
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: ~ 2016年5月9日 mdavey 撰写。
- en: Posted in [Data](https://mdavey.wordpress.com/category/data/)
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 发布在 [数据](https://mdavey.wordpress.com/category/data/) 分类下
