- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-18 16:38:25'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 16:38:25
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'VIX and More: The Story of VIX ETPs Relative to their Intraday Indicative Values'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: VIX和更多：VIX ETP与其盘中指示价值的故事
- en: 来源：[http://vixandmore.blogspot.com/2012/02/story-of-vix-etps-relative-to-their.html#0001-01-01](http://vixandmore.blogspot.com/2012/02/story-of-vix-etps-relative-to-their.html#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[http://vixandmore.blogspot.com/2012/02/story-of-vix-etps-relative-to-their.html#0001-01-01](http://vixandmore.blogspot.com/2012/02/story-of-vix-etps-relative-to-their.html#0001-01-01)
- en: This week has seen an explosion of interest in the [VIX exchange-traded product](http://vixandmore.blogspot.com/search/label/VIX%20ETN)
    (ETP) space, most of which has been due to the suspension by Credit Suisse ([CS](http://vixandmore.blogspot.com/search/label/CS))
    of creation units (think ‘new shares’) in the VelocityShares Daily 2x VIX Short-Term
    ETNs ([TVIX](http://vixandmore.blogspot.com/search/label/TVIX)).
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 本周见证了VIX交易所交易产品（ETP）空间兴趣的爆炸，这大部分是由于Credit Suisse（[CS](http://vixandmore.blogspot.com/search/label/CS)）暂停了VelocityShares每日2x
    VIX短期ETNs ([TVIX](http://vixandmore.blogspot.com/search/label/TVIX))的创建单位（想想“新股份”）。
- en: 'For those who are late to the story and/or would like some background, the
    links below should suffice, but for today I am interested in some data that might
    indicate how much stress there is in the market for TVIX shares, for VelocityShares
    products other than TVIX and for a ProShares product that is similar to TVIX,
    but is an ETF rather than an ETN: the ProShares Ultra VIX Short-Term Futures ETF,
    [UVXY](http://vixandmore.blogspot.com/search/label/UVXY).'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 对于那些对故事了解较晚的人以及/或者需要一些背景知识的人，下面的链接应该足够了，但今天我感兴趣的是某些数据，这些数据可能表明TVIX股份市场、VelocityShares除TVIX之外的产品以及一种与TVIX类似但却是ETF而非ETN的ProShares产品市场压力有多大：ProShares
    Ultra VIX Short-Term Futures ETF，[UVXY](http://vixandmore.blogspot.com/search/label/UVXY)。
- en: For this analysis, I have evaluated the prices of a handful of VIX ETPs relative
    to their [Intraday Indicative Value](http://vixandmore.blogspot.com/search/label/intraday%20indicative%20value)
    (a real-time estimate of an ETP’s fair value, based on the most recent prices
    of its underlying securities) for the last week. The graphic below shows the premium
    for five VIX ETPs as a percentage of their indicative values, normalized to a
    100 point scale.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 对于此分析，我已经评估了过去一周内少数VIX ETP相对于其[盘中指示价值](http://vixandmore.blogspot.com/search/label/intraday%20indicative%20value)（基于其基础证券最近价格的实时估计，是ETP的公允价值）的价格。下图显示了五个VIX
    ETP的溢价（相对于其指示价值）百分比，标准化为100点刻度。
- en: The chart shows that prior to the [suspension of new creation units](http://vixandmore.blogspot.com/2012/02/credit-suisse-suspends-creation-units.html)
    in TVIX after the close of regular trading on Tuesday, February 21^(st), these
    VIX ETPs generally traded very close to their indicative values. In fact, the
    norm for the long ETPs (TVIX, UVXY, [VXX](http://vixandmore.blogspot.com/search/label/VXX)
    and [VIIX](http://vixandmore.blogspot.com/search/label/VIIX)) was to trade at
    a slight premium to the indicative value, generally less than 1% higher. By contrast,
    the one inverse ETP on the list, [XIV](http://vixandmore.blogspot.com/search/label/XIV),
    tended to trade at a slight discount to indicative value, again, generally less
    than 1%.
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 图表显示，在2月21日星期二 regular trading收盘后，TVIX停止新的创建单位之前，这些VIX ETP通常交易于其指示价值非常接近。实际上，对于长期ETP（TVIX，UVXY，[VXX](http://vixandmore.blogspot.com/search/label/VXX)和[VIIX](http://vixandmore.blogspot.com/search/label/VIIX)）来说，交易于指示价值略微溢价是常态，通常不超过1%的溢价。相比之下，列表中唯一的反向ETP
    [XIV](http://vixandmore.blogspot.com/search/label/XIV)倾向于以略微折价交易于指示价值，同样，通常不超过1%。
- en: Once Credit Suisse closed the door for new creation units, the price of TVIX
    has drifted steadily higher relative to its indicative value, even trading at
    a 20% premium just a few minutes ago.
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 一旦Credit Suisse关闭了新的创建单位的大门，TVIX的价格相对于其指示价值稳步上升，甚至在几分钟前还交易于20%的溢价。
- en: In terms of other market dislocations, however, the evidence is not compelling.
    UVXY, which is an excellent substitute for TVIX, doubled its prior record volume
    yesterday and is on schedule to top that today, but after seeing a slight lift
    in the premium relative to indicative value, UVXY’s premium is now back to historical
    norms.
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 然而，在其他市场扭曲方面，证据并不令人信服。UVXY，作为TVIX的优秀替代品，昨天的成交量是其先前记录的两倍，并且今天有望超过这个数字，但在指示价值相对溢价的轻微提升之后，UVXY的溢价现在已回到历史常态。
- en: Looking at some of the other VelocityShares products, the two next most popular
    after TVIX are XIV and VIIX. Here again, there have been some minor fluctuations
    since the Credit Suisse announcement, but nothing that has pushed these products
    more than 1% away from their indicative value.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 观察VelocityShares的其他产品，在TVIX之后最受欢迎的两个是XIV和VIIX。同样，自 Credit Suisse 宣布以来，这些产品也有一些小的波动，但没有使这些产品偏离其指示性价值超过1%。
- en: Based on the indicative value data, then, so far the only market dislocation
    has been in the TVIX product, with no evidence of a spread to competing products
    (UVXY) or other products in the VelocityShares stable, such as XIV or VIIX.
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: 基于指示性价值数据，到目前为止，市场错位仅限于TVIX产品，没有证据表明其影响到竞争产品（UVXY）或其他VelocityShares系列产品，如XIV或VIIX。
- en: 'Related posts:'
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 相关文章：
- en: '*![](img/c9f03e70ecace4e6e53e8b5ff247b794.png)*'
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: '![](img/c9f03e70ecace4e6e53e8b5ff247b794.png)'
- en: '*[source(s): Yahoo, VIX and More]*'
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: 来源：[Yahoo, VIX and More]
- en: '***Disclosure(s):*** *long XIV; short TVIX, UVXY and VXX at time of writing*'
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: '***披露(s):*** *在撰写本文时持有XIV多头头寸；持有TVIX、UVXY和VXX的空头头寸*'
