- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 18:06:02'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'VIX and More: Selling Naked Puts in Current Environment'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[http://vixandmore.blogspot.com/2009/01/selling-naked-puts-in-current.html#0001-01-01](http://vixandmore.blogspot.com/2009/01/selling-naked-puts-in-current.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: During my recent [trilogy](http://vixandmore.blogspot.com/2009/01/more-on-put-returns.html)
    on the [put-write](http://vixandmore.blogspot.com/search/label/put-write) strategy,
    my intent was to identify an approach that performs well in a non-trending market.
    While I still believe we are stuck in a range defined by about 820-980 on the
    S&P 500 index, a strategy that involves selling puts generally performs at maximum
    levels toward the bottom of a well-defined trading range. In short, the current
    situation looks like an excellent time to write some cash-secured puts.
  prefs: []
  type: TYPE_NORMAL
- en: Several factors indicate that the timing for put sales may be ideal right now.
    With the VIX up over 51 once again as the market opens this morning and most measures
    of short-term [historical volatility](http://vixandmore.blogspot.com/search/label/historical%20volatility)
    (such as the 10 day HV in the chart below) showing that the VIX is well above
    actual volatility we have experienced during the past few weeks, a likely conclusion
    is that volatility is overpriced at current levels. Further, with the SPX right
    at 830 as I type this, we are near the bottom of the trading range in the SPX,
    with significant support likely to be found in the 820-830 range.
  prefs: []
  type: TYPE_NORMAL
- en: Finally, the news flow has been so negative lately, from financials to retailers
    to Steve Jobs to global trade, etc. that a larger fear and anxiety component is
    starting to creep into [implied volatility](http://vixandmore.blogspot.com/search/label/implied%20volatility)
    measures like the VIX.
  prefs: []
  type: TYPE_NORMAL
- en: For those looking to limit risk, cash-secured puts on indices or ETFs covering
    a group of stocks can help to eliminate single stock down side risk. Those who
    are interested in limiting risk from writing puts may prefer to look at a [bull
    put spread](http://vixandmore.blogspot.com/search/label/bull%20put%20spread),
    where the writer sells a put near the money and buys another out of the money
    put to limit losses.
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/57a3ec7b5397b82efe66033b9a655002.png)'
  prefs: []
  type: TYPE_IMG
- en: '*[source: VIX and More]*'
  prefs: []
  type: TYPE_NORMAL
