- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 18:23:48'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'VIX and More: Environmental Factors and Chart Reading'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[http://vixandmore.blogspot.com/2008/10/environmental-factors-and-chart-reading.html#0001-01-01](http://vixandmore.blogspot.com/2008/10/environmental-factors-and-chart-reading.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: I happen to think that charts provide important clues to the behavior of participants
    in the various financial markets.
  prefs: []
  type: TYPE_NORMAL
- en: Of course there are many ways to read a stock chart and consequently it can
    be more of an art than a science, so when I see some related scientific studies,
    I tend to take note of their conclusions. One example is [Do You Want to Believe?](http://www.sciencefriday.com/program/archives/200810037)
    which appeared today in Science Friday.com and discusses an experiment in which
    subjects had varying degrees of control over their situation and were tested on
    how likely they were to see imaginary images embedded in snowy pictures
  prefs: []
  type: TYPE_NORMAL
- en: 'Jennifer Whitson, one of the authors of the report, describes the findings
    as follows:'
  prefs: []
  type: TYPE_NORMAL
- en: '*“People see false patterns in all types of data, imagining trends in stock
    markets, seeing faces in static, and detecting conspiracies between acquaintances.
    This suggests that lacking control leads to a visceral need for order – even imaginary
    order.”*'
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'The bottom line: if your investments have been faring poorly lately and you
    have had trouble reading the trends, make an effort not to be overly reliant on
    charts – or at least make sure to use a consistent quantitatively-based approach
    to analyzing those charts.'
  prefs: []
  type: TYPE_NORMAL
