- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-18 18:06:02'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-18 18:06:02
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'VIX and More: Selling Naked Puts in Current Environment'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: VIX和更多：当前环境下的裸看跌期权出售
- en: 来源：[http://vixandmore.blogspot.com/2009/01/selling-naked-puts-in-current.html#0001-01-01](http://vixandmore.blogspot.com/2009/01/selling-naked-puts-in-current.html#0001-01-01)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[http://vixandmore.blogspot.com/2009/01/selling-naked-puts-in-current.html#0001-01-01](http://vixandmore.blogspot.com/2009/01/selling-naked-puts-in-current.html#0001-01-01)
- en: During my recent [trilogy](http://vixandmore.blogspot.com/2009/01/more-on-put-returns.html)
    on the [put-write](http://vixandmore.blogspot.com/search/label/put-write) strategy,
    my intent was to identify an approach that performs well in a non-trending market.
    While I still believe we are stuck in a range defined by about 820-980 on the
    S&P 500 index, a strategy that involves selling puts generally performs at maximum
    levels toward the bottom of a well-defined trading range. In short, the current
    situation looks like an excellent time to write some cash-secured puts.
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 在我的最近[三部曲](http://vixandmore.blogspot.com/2009/01/more-on-put-returns.html)关于[看跌期权写作](http://vixandmore.blogspot.com/search/label/put-write)策略中，我的意图是识别一个在非趋势市场中表现良好的方法。尽管我仍然相信我们被困在标普500指数大约820-980的范围内，但涉及出售看跌期权的方法在定义良好的交易区间的底部时通常表现最佳。简而言之，当前情况看起来是写一些现金担保看跌期权的绝佳时机。
- en: Several factors indicate that the timing for put sales may be ideal right now.
    With the VIX up over 51 once again as the market opens this morning and most measures
    of short-term [historical volatility](http://vixandmore.blogspot.com/search/label/historical%20volatility)
    (such as the 10 day HV in the chart below) showing that the VIX is well above
    actual volatility we have experienced during the past few weeks, a likely conclusion
    is that volatility is overpriced at current levels. Further, with the SPX right
    at 830 as I type this, we are near the bottom of the trading range in the SPX,
    with significant support likely to be found in the 820-830 range.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 有几个因素表明，目前可能是出售看跌期权的好时机。随着市场开盘今晨VIX再次超过51，并且大多数短期[历史波动率](http://vixandmore.blogspot.com/search/label/historical%20volatility)（如图表下的10日HV）显示VIX远高于我们过去几周实际经历的市场波动率，一个可能的结论是，当前水平的波动率被高估了。此外，在我写下这些内容时，SPX正好在830，我们正处于SPX交易区间的底部，820-830区间可能有重要的支撑。
- en: Finally, the news flow has been so negative lately, from financials to retailers
    to Steve Jobs to global trade, etc. that a larger fear and anxiety component is
    starting to creep into [implied volatility](http://vixandmore.blogspot.com/search/label/implied%20volatility)
    measures like the VIX.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 最后，最近新闻流动一直很负面，从金融股到零售商，从史蒂夫·乔布斯到全球贸易等。这种更大的恐惧和焦虑成分开始渗透到像VIX这样的[隐含波动率](http://vixandmore.blogspot.com/search/label/implied%20volatility)指标中。
- en: For those looking to limit risk, cash-secured puts on indices or ETFs covering
    a group of stocks can help to eliminate single stock down side risk. Those who
    are interested in limiting risk from writing puts may prefer to look at a [bull
    put spread](http://vixandmore.blogspot.com/search/label/bull%20put%20spread),
    where the writer sells a put near the money and buys another out of the money
    put to limit losses.
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 对于那些想要限制风险的人来说，针对一组股票的指数或ETF的现金担保看跌期权可以帮助消除单一股票的下行风险。那些有兴趣限制写看跌期权风险的人可能更愿意考虑[牛市看跌价差](http://vixandmore.blogspot.com/search/label/bull%20put%20spread)，在这种策略中，作者出售一个接近价钱的看跌期权并购买另一个远离价钱的看跌期权以限制损失。
- en: '![](img/57a3ec7b5397b82efe66033b9a655002.png)'
  id: totrans-10
  prefs: []
  type: TYPE_IMG
  zh: '![](img/57a3ec7b5397b82efe66033b9a655002.png)'
- en: '*[source: VIX and More]*'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 来源：[VIX和更多](http://vixandmore.blogspot.com/)
