- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-18 18:51:12'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'VIX and More: Neighborhood Home Values Holding Up Nicely'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[http://vixandmore.blogspot.com/2007/12/neighborhood-home-values-holding-up.html#0001-01-01](http://vixandmore.blogspot.com/2007/12/neighborhood-home-values-holding-up.html#0001-01-01)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: '![](img/d32ebda832160a4689413465ddcd9420.png)A month ago, in [The Other Bubble](http://vixandmore.blogspot.com/2007/11/other-bubble.html),
    I mentioned that I live in <placename st="on">Marin</placename> <placetype st="on">County</placetype>,
    just north of <city st="on"><place st="on">San Francisco</place></city> and commented
    on the surprising strength of the local real estate market.  Well, things appear
    to be better than I thought.'
  prefs: []
  type: TYPE_NORMAL
- en: Amidst all the talk of the subprime meltdown and impending financial calamities,
    I found it interesting that not too far from where I live, a house has apparently
    just gone into contract for $65 million – the full asking price.  The Wall Street
    Journal broke the [story](http://online.wsj.com/article/SB119757552962127329.html?mod=pj_main_hs_coll)
    this morning, but an old Forbes profile of [The Most Expensive House in California](http://www.forbes.com/2005/02/28/cx_sc_0228how.html)
    is a better stop to read more about [Locksley Hall](http://www.suzmancole.com/portfolio/residential/traditional/locksley.php),
    currently owned by [Robert “Toxic Bob” Friedland](http://www.forbes.com/lists/2006/10/QXNL.html),
    a global mining tycoon who earned his nickname by helping to turn [Summitville
    Mine](http://en.wikipedia.org/wiki/Summitville_mine) into one of the most notorious
    [Superfund](http://en.wikipedia.org/wiki/Superfund) sites.
  prefs: []
  type: TYPE_NORMAL
- en: While I mentioned on Wednesday that I have had a good run with my trading lately,
    I hasten to add that I am ***not*** the buyer.  So far, the buyer's name has not
    been disclosed.  One locally famous name worth noting, however, is [Olivia Hsu
    Decker](http://www.sfgate.com/cgi-bin/article.cgi?f=/c/a/2006/04/09/CMGU1HQ4PR1.DTL&hw=malin+giddings&sn=001&sc=1000),
    who handled the listing and whose [web site](http://www.sanfranciscofinehomes.com/)
    makes for interesting browsing if you are into house envy.
  prefs: []
  type: TYPE_NORMAL
- en: Friedland has renovated the original house extensively and various sources list
    the current square footage at 10,000 or 12,000.  I must say, however, that $6,000
    per square foot is not outrageous [for the area](http://www.trulia.com/CA/Belvedere/#for_sale/Belvedere,CA/price;d_sort/),
    especially considering that the views from the site are generally considered to
    be in the top five in the world.
  prefs: []
  type: TYPE_NORMAL
- en: If nothing else, this transaction will make for some interesting average home
    sale price statistics in the area. Perhaps some day I can try to sneak it in as
    a comp...
  prefs: []
  type: TYPE_NORMAL
